In [2]:
from pathlib import Path
import json
import re
from collections import Counter
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
BASE_DIR = Path("../matsne_data")
SEARCH_DIR = BASE_DIR / "search_pages"
RAW_DIR = BASE_DIR / "documents_raw"
OUTPUT_FILE = BASE_DIR / "documents.jsonl"
FAILED_FILE = BASE_DIR / "failed_documents.json"

# Load JSONL
docs = []

with OUTPUT_FILE.open("r", encoding="utf-8") as f:
    for line_number, line in enumerate(f, start=1):
        line = line.strip()
        if not line:
            continue
        
        try:
            docs.append(json.loads(line))
        except json.JSONDecodeError as e:
            print(f"JSON error on line {line_number}: {e}")

print(f"Documents loaded: {len(docs):,}")

Documents loaded: 300

# Basic Checks

In [4]:
ids = [d.get("document_id") for d in docs]
titles = [d.get("title") for d in docs]
urls = [d.get("url") for d in docs]

print("=== BASIC INTEGRITY ===")
print(f"Documents:       {len(docs):,}")
print(f"Unique IDs:      {len(set(ids)):,}")
print(f"Duplicate IDs:   {len(ids) - len(set(ids)):,}")
print(f"Unique URLs:     {len(set(urls)):,}")
print(f"Duplicate URLs:  {len(urls) - len(set(urls)):,}")
print(f"Missing IDs:     {sum(x is None or x == '' for x in ids):,}")
print(f"Missing titles:  {sum(x is None or x == '' for x in titles):,}")
print(f"Missing URLs:    {sum(x is None or x == '' for x in urls):,}")

=== BASIC INTEGRITY ===
Documents:       300
Unique IDs:      300
Duplicate IDs:   0
Unique URLs:     300
Duplicate URLs:  0
Missing IDs:     0
Missing titles:  0
Missing URLs:    0

# Check Failures

In [5]:
if FAILED_FILE.exists():
    failed = json.loads(FAILED_FILE.read_text(encoding="utf-8"))
else:
    failed = []

print("=== DOWNLOAD FAILURES ===")
print(f"Failed documents: {len(failed)}")

if failed:
    display(pd.DataFrame(failed))

=== DOWNLOAD FAILURES ===
Failed documents: 0

# Check raw HTML - JSONL

In [6]:
json_ids = set(ids)

raw_ids = {
    path.stem
    for path in RAW_DIR.glob("*.html")
}

missing_raw = json_ids - raw_ids
extra_raw = raw_ids - json_ids

print("=== RAW HTML INTEGRITY ===")
print(f"JSON documents:       {len(json_ids):,}")
print(f"Raw HTML files:       {len(raw_ids):,}")
print(f"JSON IDs without raw: {len(missing_raw):,}")
print(f"Raw files without JSON: {len(extra_raw):,}")

if missing_raw:
    print("\nMissing raw HTML:")
    print(sorted(missing_raw)[:20])

if extra_raw:
    print("\nExtra raw HTML:")
    print(sorted(extra_raw)[:20])

=== RAW HTML INTEGRITY ===
JSON documents:       300
Raw HTML files:       300
JSON IDs without raw: 0
Raw files without JSON: 0

In [7]:
def extract_search_ids(path):
    html = path.read_text(encoding="utf-8")
    soup = BeautifulSoup(html, "html.parser")
    
    result_items = soup.select("div.document-search-result-item")
    
    found = []
    
    for item in result_items:
        link = item.select_one(".panel-heading a")
        if not link:
            continue
        
        href = link.get("href", "")
        match = re.search(r"/document/view/(\d+)", href)
        
        if match:
            found.append(match.group(1))
    
    return found


search_ids_by_page = {}

for path in sorted(SEARCH_DIR.glob("page_*.html")):
    page_ids = extract_search_ids(path)
    page_number = int(re.search(r"page_(\d+)", path.name).group(1))
    search_ids_by_page[page_number] = page_ids
    
    print(
        f"Page {page_number}: "
        f"{len(page_ids)} results, "
        f"{len(set(page_ids))} unique IDs"
    )

search_ids = [
    document_id
    for page_ids in search_ids_by_page.values()
    for document_id in page_ids
]

search_id_set = set(search_ids)
json_id_set = set(ids)

print("\n=== SEARCH ↔ CORPUS ===")
print(f"Search result records: {len(search_ids):,}")
print(f"Unique search IDs:     {len(search_id_set):,}")
print(f"Corpus IDs:            {len(json_id_set):,}")

print(f"Search IDs missing from corpus: {len(search_id_set - json_id_set):,}")
print(f"Corpus IDs not in search:       {len(json_id_set - search_id_set):,}")

Page 1: 100 results, 100 unique IDs
Page 2: 100 results, 100 unique IDs
Page 3: 100 results, 100 unique IDs
Page 4: 100 results, 100 unique IDs
Page 5: 100 results, 100 unique IDs

=== SEARCH ↔ CORPUS ===
Search result records: 500
Unique search IDs:     500
Corpus IDs:            300
Search IDs missing from corpus: 200
Corpus IDs not in search:       0

# Metadata

In [8]:
metadata_fields = [
    "document_id",
    "title",
    "url",
    "language",
    "document_type",
    "issuing_authority",
    "document_number",
    "signing_date",
]

print("=== METADATA COMPLETENESS ===")

metadata_report = []

for field in metadata_fields:
    missing = sum(
        d.get(field) is None or str(d.get(field)).strip() == ""
        for d in docs
    )
    
    metadata_report.append({
        "field": field,
        "missing": missing,
        "complete": len(docs) - missing,
        "completeness_%": round(
            100 * (len(docs) - missing) / len(docs), 2
        )
    })

display(pd.DataFrame(metadata_report))

=== METADATA COMPLETENESS ===

               field  missing  complete  completeness_%
0        document_id        0       300           100.0
1              title        0       300           100.0
2                url        0       300           100.0
3           language        0       300           100.0
4      document_type        0       300           100.0
5  issuing_authority        0       300           100.0
6    document_number        0       300           100.0
7       signing_date        0       300           100.0

# Length

In [9]:
text_lengths = []

for d in docs:
    text = d.get("text") or ""
    
    text_lengths.append({
        "document_id": d["document_id"],
        "title": d["title"],
        "characters": len(text),
        "words": len(text.split()),
        "parts": d.get("part_count", 0),
    })

text_df = pd.DataFrame(text_lengths)

print("=== TEXT INTEGRITY ===")
print(f"Empty documents:        {(text_df['characters'] == 0).sum()}")
print(f"<100 characters:        {(text_df['characters'] < 100).sum()}")
print(f"<500 characters:        {(text_df['characters'] < 500).sum()}")
print(f"<1,000 characters:      {(text_df['characters'] < 1000).sum()}")

print("\nText length statistics:")
display(text_df["characters"].describe())

=== TEXT INTEGRITY ===
Empty documents:        0
<100 characters:        0
<500 characters:        4
<1,000 characters:      33

Text length statistics:

count       300.000000
mean      23457.540000
std       43892.558448
min         434.000000
25%        2993.500000
50%       11834.000000
75%       32370.500000
max      611489.000000
Name: characters, dtype: float64

In [10]:
short_docs = (
    text_df
    .sort_values("characters")
    .head(20)
)

display(short_docs)

,document_id,title,characters,words,parts
283,5739890,მნიშვნელოვანი ქონებით უზრუნველყოფილი ფიზიკური ...,434,45,5
278,5762493,„ტურისტული მომსახურების დღგ-ით დაბეგვრის თაობა...,478,52,5
142,6231728,ბუღალტრისა და აუდიტორის პროფესიული დღის განსაზ...,483,51,6
282,5749638,„ყულევის თავისუფალი ინდუსტრიული ზონის შექმნის ...,497,52,5
100,6562716,„საქართველოს საჯარო სექტორის ბუღალტრული აღრიცხ...,523,54,5
202,5958945,“ელექტრონული კომერციის შესახებ” საქართველოს კა...,562,63,5
11,6933818,„სახელმწიფო სამეცნიერო გრანტების გაცემის შესახ...,597,62,5
38,6810516,საინვესტიციო ოქროს სტატუსის დადგენის დამატებით...,610,70,5
26,6865118,„სს „საქართველოს განვითარების ფონდის“ წესდების...,635,68,5
34,6827122,საქართველოს ეროვნული ბანკის ზედამხედველობას და...,686,76,5
182,6086072,საგარეო-ეკონომიკური საქმიანობის ეროვნული სასაქ...,712,77,6
253,5835097,მიკრობანკებისათვის საზედამხედველო კაპიტალის მი...,714,80,5
13,6903799,„საქართველოს ფინანსთა სამინისტროს ცენტრალური ა...,742,76,5
118,6377781,დასაქმების ხელშეწყობის 2025 წლის სახელმწიფო პრ...,744,77,5
258,5835108,მიკრობანკებისთვის კონტრციკლური ბუფერის განაკვე...,765,85,6
25,6869054,„საჯარო სამართლის იურიდიული პირის – აწარმოე სა...,769,89,5
265,5800025,„მნიშვნელოვანი ქონებით უზრუნველყოფილი ფიზიკური...,773,79,5
291,5723520,სახელმწიფო საწარმოთა სექტორიზაციის რეესტრის და...,815,83,6
40,6808331,საქართველოს ფინანსთა სამინისტროს საგამოძიებო ს...,828,82,6
299,5662765,საქართველოს გარემოს დაცვისა და სოფლის მეურნეობ...,846,93,9

# Integrity

In [11]:
print("=== PART INTEGRITY ===")

zero_parts = [
    d for d in docs
    if not d.get("parts")
]

zero_part_count = len(zero_parts)

empty_parts = []

for d in docs:
    for part in d.get("parts", []):
        if not (part.get("text") or "").strip():
            empty_parts.append({
                "document_id": d["document_id"],
                "title": d["title"],
                "part_id": part.get("id"),
                "type": part.get("type"),
                "structure": part.get("structure"),
            })

print(f"Documents with zero parts: {zero_part_count}")
print(f"Empty parts:               {len(empty_parts)}")

if empty_parts:
    display(pd.DataFrame(empty_parts).head(50))

=== PART INTEGRITY ===
Documents with zero parts: 0
Empty parts:               689

,document_id,title,part_id,type,structure
0,7010313,საქართველოს ეროვნული ბანკის 2026-2027 წლების ა...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
1,7010249,სახელმწიფო აუდიტის სამსახურის 2026-2027 წლების...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
2,7002597,ადმინისტრაციული სახდელისგან გათავისუფლების შეს...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
3,6987795,სახელმწიფო შესყიდვის დარეზერვების წესისა და პი...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
4,6987795,სახელმწიფო შესყიდვის დარეზერვების წესისა და პი...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
5,6987795,სახელმწიფო შესყიდვის დარეზერვების წესისა და პი...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"
6,6981470,ვირტუალური აქტივის მომსახურების პროვაიდერის მი...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, HEADER:1]"
7,6981470,ვირტუალური აქტივის მომსახურების პროვაიდერის მი...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
8,6981470,ვირტუალური აქტივის მომსახურების პროვაიდერის მი...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"
9,6969117,ფასიანი ქაღალდების რეგისტრატორის და საბროკერო ...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
10,6969117,ფასიანი ქაღალდების რეგისტრატორის და საბროკერო ...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"
11,6969072,პირების მიმართ ფასიანი ქაღალდების შესახებ კანო...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
12,6969072,პირების მიმართ ფასიანი ქაღალდების შესახებ კანო...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"
13,6961997,„საინვესტიციო ფონდების მხარდაჭერის სახელმწიფო ...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
14,6961997,„საინვესტიციო ფონდების მხარდაჭერის სახელმწიფო ...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
15,6961997,„საინვესტიციო ფონდების მხარდაჭერის სახელმწიფო ...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"
16,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, HEADER:1]"
17,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
18,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"
19,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:2;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:2, PREAMBLE:1]"
20,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:2;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:2, FOOTER:1]"
21,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:3;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:3, PREAMBLE:1]"
22,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:3;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:3, FOOTER:1]"
23,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:4;HEADER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:4, HEADER:1]"
24,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:4;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:4, PREAMBLE:1]"
25,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:4;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:4, FOOTER:1]"
26,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:5;HEADER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:5, HEADER:1]"
27,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:5;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:5, PREAMBLE:1]"
28,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:5;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:5, FOOTER:1]"
29,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:6;HEADER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:6, HEADER:1]"
30,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:6;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:6, PREAMBLE:1]"
31,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:6;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:6, FOOTER:1]"
32,6933818,„სახელმწიფო სამეცნიერო გრანტების გაცემის შესახ...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
33,6906141,აგროთანადაფინანსების სახელმწიფო პროგრამის დამტ...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
34,6885351,ფინანსური ანგარიშგების საერთაშორისო სტანდარტებ...,DOCUMENT:1;ARTICLE:1;_Content,ARTICLE,"[DOCUMENT:1, ARTICLE:1]"
35,6884261,საჯარო სამართლის იურიდიული პირის − გარემოსდაცვ...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
36,6883523,ინფრასტრუქტურული პროექტების განხორციელების ხელ...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
37,6883523,ინფრასტრუქტურული პროექტების განხორციელების ხელ...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, HEADER:1]"
38,6883523,ინფრასტრუქტურული პროექტების განხორციელების ხელ...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
39,6883523,ინფრასტრუქტურული პროექტების განხორციელების ხელ...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"
40,6880931,ტექნიკური რეგლამენტის − სამშენებლო სამუშაოების...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
41,6880931,ტექნიკური რეგლამენტის − სამშენებლო სამუშაოების...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
42,6880931,ტექნიკური რეგლამენტის − სამშენებლო სამუშაოების...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"
43,6878133,ცენტრალური შემსყიდველი ორგანოს მიერ ბაზრის კვლ...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
44,6878133,ცენტრალური შემსყიდველი ორგანოს მიერ ბაზრის კვლ...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
45,6878133,ცენტრალური შემსყიდველი ორგანოს მიერ ბაზრის კვლ...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"
46,6878077,ცენტრალიზებული შესყიდვების განხორციელებასთან დ...,DOCUMENT:1;PREAMBLE:1;_Content,PREAMBLE,"[DOCUMENT:1, PREAMBLE:1]"
47,6878077,ცენტრალიზებული შესყიდვების განხორციელებასთან დ...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, HEADER:1]"
48,6878077,ცენტრალიზებული შესყიდვების განხორციელებასთან დ...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, PREAMBLE:1]"
49,6878077,ცენტრალიზებული შესყიდვების განხორციელებასთან დ...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,"[DOCUMENT:1, ENCLOSURE:1, FOOTER:1]"

# Structure

In [12]:
part_types = Counter()

for d in docs:
    for part in d.get("parts", []):
        part_types[part.get("type")] += 1

print("=== PART TYPES ===")

part_type_df = (
    pd.DataFrame(
        part_types.items(),
        columns=["type", "count"]
    )
    .sort_values("count", ascending=False)
)

display(part_type_df)

=== PART TYPES ===

        type  count
5  ENCLOSURE   1460
4    ARTICLE    845
0     HEADER    300
3     FOOTER    300
1   PREAMBLE    300
6    CHAPTER    174
2      POINT     24

In [13]:
enclosure_parts = []

for d in docs:
    for part in d.get("parts", []):
        if part.get("enclosure") is not None:
            enclosure_parts.append({
                "document_id": d["document_id"],
                "title": d["title"],
                "part_id": part.get("id"),
                "type": part.get("type"),
                "enclosure": part.get("enclosure"),
                "structure": " > ".join(part.get("structure", [])),
                "characters": len(part.get("text") or ""),
            })

print(f"Parts belonging to enclosures: {len(enclosure_parts)}")

if enclosure_parts:
    enclosure_df = pd.DataFrame(enclosure_parts)
    display(enclosure_df.head(30))

Parts belonging to enclosures: 1460

,document_id,title,part_id,type,enclosure,structure,characters
0,6987795,სახელმწიფო შესყიდვის დარეზერვების წესისა და პი...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > HEADER:1,50
1,6987795,სახელმწიფო შესყიდვის დარეზერვების წესისა და პი...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > PREAMBLE:1,0
2,6987795,სახელმწიფო შესყიდვის დარეზერვების წესისა და პი...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:1,8079
3,6987795,სახელმწიფო შესყიდვის დარეზერვების წესისა და პი...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > FOOTER:1,0
4,6981470,ვირტუალური აქტივის მომსახურების პროვაიდერის მი...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > HEADER:1,0
5,6981470,ვირტუალური აქტივის მომსახურების პროვაიდერის მი...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > PREAMBLE:1,0
6,6981470,ვირტუალური აქტივის მომსახურების პროვაიდერის მი...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:1,8611
7,6981470,ვირტუალური აქტივის მომსახურების პროვაიდერის მი...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > FOOTER:1,0
8,6969117,ფასიანი ქაღალდების რეგისტრატორის და საბროკერო ...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > HEADER:1,278
9,6969117,ფასიანი ქაღალდების რეგისტრატორის და საბროკერო ...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > PREAMBLE:1,0
10,6969117,ფასიანი ქაღალდების რეგისტრატორის და საბროკერო ...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:1,33043
11,6969117,ფასიანი ქაღალდების რეგისტრატორის და საბროკერო ...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > FOOTER:1,0
12,6969072,პირების მიმართ ფასიანი ქაღალდების შესახებ კანო...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > HEADER:1,219
13,6969072,პირების მიმართ ფასიანი ქაღალდების შესახებ კანო...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > PREAMBLE:1,0
14,6969072,პირების მიმართ ფასიანი ქაღალდების შესახებ კანო...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:1,51387
15,6969072,პირების მიმართ ფასიანი ქაღალდების შესახებ კანო...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > FOOTER:1,0
16,6961997,„საინვესტიციო ფონდების მხარდაჭერის სახელმწიფო ...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > HEADER:1,77
17,6961997,„საინვესტიციო ფონდების მხარდაჭერის სახელმწიფო ...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > PREAMBLE:1,0
18,6961997,„საინვესტიციო ფონდების მხარდაჭერის სახელმწიფო ...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:1,19951
19,6961997,„საინვესტიციო ფონდების მხარდაჭერის სახელმწიფო ...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > FOOTER:1,0
20,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;HEADER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > HEADER:1,0
21,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;PREAMBLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > PREAMBLE:1,0
22,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:1,1725
23,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:2;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:2,444
24,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:3;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:3,1527
25,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:4;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:4,1807
26,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:5;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:5,1818
27,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;ARTICLE:6;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:6,685
28,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:1;FOOTER:1;_Content,ENCLOSURE,1,DOCUMENT:1 > ENCLOSURE:1 > FOOTER:1,0
29,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,DOCUMENT:1;ENCLOSURE:2;HEADER:1;_Content,ENCLOSURE,2,DOCUMENT:1 > ENCLOSURE:2 > HEADER:1,50

# HTML Leakage

In [14]:
html_patterns = [
    r"<[a-zA-Z][^>]*>",
    r"</[a-zA-Z]+>",
    r"&nbsp;",
    r"&amp;",
]

html_leaks = []

for d in docs:
    text = d.get("text") or ""
    
    matches = []
    
    for pattern in html_patterns:
        matches.extend(re.findall(pattern, text))
    
    if matches:
        html_leaks.append({
            "document_id": d["document_id"],
            "title": d["title"],
            "matches": matches[:10],
        })

print(f"Documents with possible HTML leakage: {len(html_leaks)}")

if html_leaks:
    display(pd.DataFrame(html_leaks).head(30))

Documents with possible HTML leakage: 0

# Georgian chars

In [15]:
def georgian_char_count(text):
    return len(re.findall(r"[ა-ჰ]", text))

def latin_char_count(text):
    return len(re.findall(r"[A-Za-z]", text))

def cyrillic_char_count(text):
    return len(re.findall(r"[А-Яа-я]", text))


script_rows = []

for d in docs:
    text = d.get("text") or ""
    
    script_rows.append({
        "document_id": d["document_id"],
        "title": d["title"],
        "characters": len(text),
        "georgian": georgian_char_count(text),
        "latin": latin_char_count(text),
        "cyrillic": cyrillic_char_count(text),
    })

script_df = pd.DataFrame(script_rows)

script_df["georgian_ratio"] = (
    script_df["georgian"] /
    script_df["characters"].replace(0, 1)
)

print("=== SCRIPT SANITY ===")

print(
    f"Documents with zero Georgian characters: "
    f"{(script_df['georgian'] == 0).sum()}"
)

print(
    f"Documents with <1% Georgian characters: "
    f"{(script_df['georgian_ratio'] < 0.01).sum()}"
)

display(
    script_df
    .sort_values("georgian_ratio")
    .head(20)
)

=== SCRIPT SANITY ===
Documents with zero Georgian characters: 0
Documents with <1% Georgian characters: 0

,document_id,title,characters,georgian,latin,cyrillic,georgian_ratio
207,5936431,მსოფლიო ბანკთაშორისი საფინანსო ტელეკომუნიკაციე...,12363,7335,2873,0,0.593303
129,6320610,საჯარო სამართლის იურიდიული პირის − საქართველოს...,69068,47705,11050,0,0.690696
80,6703385,აჭარის ავტონომიური რესპუბლიკის კანონი აჭარის ა...,129739,91892,38,0,0.708284
159,6156028,საზოგადოებრივი ჯანმრთელობის დელეგირებული უფლებ...,8197,5864,232,2,0.715384
79,6710623,აფხაზეთის ავტონომიური რესპუბლიკის 2026 წლის რე...,86196,64194,49,0,0.744745
1,7010249,სახელმწიფო აუდიტის სამსახურის 2026-2027 წლების...,894,682,27,0,0.762864
83,6701007,საქართველოს 2026 წლის სახელმწიფო ბიუჯეტის შესახებ,611489,467965,1872,2,0.765288
148,6206301,საქართველოს ეროვნული ბანკის 2024-2025 წლების ა...,1004,772,27,0,0.768924
91,6629760,დეპოზიტორისთვის ასანაზღაურებელი დაზღვეული დეპო...,1029,794,14,0,0.771623
62,6737639,საჯარო სამართლის იურიდიული პირის - შემოსავლები...,2164,1678,0,0,0.775416
137,6235003,აჭარის ავტონომიური რესპუბლიკის 50%-ზე მეტი წილ...,904,705,14,0,0.779867
225,5865422,საქართველოს ფინანსთა სამინისტროს მიერ ორგანიზე...,17314,13540,0,0,0.782026
209,5924122,საჯარო სამართლის იურიდიული პირის − საპენსიო სა...,1110,876,6,0,0.789189
200,5962261,კომერციული ბანკების და მიკრობანკების მიერ გადა...,39765,31389,224,0,0.789363
0,7010313,საქართველოს ეროვნული ბანკის 2026-2027 წლების ა...,1014,802,5,0,0.790927
48,6754241,საქართველოს პროკურატურის თანამშრომელთა თანამდე...,7835,6205,0,0,0.791959
206,5945453,საკრედიტო რისკების მართვის წესის დამტკიცების შ...,7397,5864,87,0,0.792754
18,6880931,ტექნიკური რეგლამენტის − სამშენებლო სამუშაოების...,35824,28432,127,0,0.793658
147,6206294,სახელმწიფო აუდიტის სამსახურის 2024-2025 წლების...,927,738,5,0,0.796117
220,5876312,„აჭარის ავტონომიური რესპუბლიკის ფინანსთა და ეკ...,897,716,0,0,0.798216

# Document types

In [16]:
print("=== DOCUMENT TYPES ===")

type_df = (
    pd.DataFrame(
        Counter(d.get("document_type") for d in docs).items(),
        columns=["document_type", "count"]
    )
    .sort_values("count", ascending=False)
)

display(type_df)

=== DOCUMENT TYPES ===

                                        document_type  count
2                   საქართველოს მთავრობის დადგენილება    104
3    საქართველოს ეროვნული ბანკის პრეზიდენტის ბრძანება     90
6                      საქართველოს მინისტრის ბრძანება     33
7   ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის...     20
1                                  საქართველოს კანონი     10
0                 საქართველოს პარლამენტის დადგენილება      8
15     საქართველოს ეროვნული ბანკის საბჭოს დადგენილება      7
4   სახელმწიფო აუდიტის სამსახურის გენერალური აუდიტ...      5
8   სახელმწიფო შესყიდვების სააგენტოს თავმჯდომარის ...      4
13  სსიპ დეპოზიტების დაზღვევის სააგენტოს უფროსის ბ...      4
16         ავტონომიური რესპუბლიკის მინისტრის ბრძანება      3
12                     ავტონომიური რესპუბლიკის კანონი      3
5   აფხაზეთის ავტონომიური რესპუბლიკის ფინანსთა და ...      2
9       ავტონომიური რესპუბლიკის მთავრობის დადგენილება      2
10  საქართველოს ფინანსური მონიტორინგის სამსახურის ...      1
14  სსიპ – სახელმწიფო გრანტის მართვის სააგენტოს თა...      1
11         საქართველოს გენერალური პროკურორის ბრძანება      1
17  საქართველოს კონკურენციის ეროვნული სააგენტოს თა...      1
18      სსიპ − ანტიკორუფციული ბიუროს უფროსის ბრძანება      1

In [17]:
print("=== ISSUING AUTHORITIES ===")

authority_df = (
    pd.DataFrame(
        Counter(d.get("issuing_authority") for d in docs).items(),
        columns=["issuing_authority", "count"]
    )
    .sort_values("count", ascending=False)
)

display(authority_df.head(30))

=== ISSUING AUTHORITIES ===

                                    issuing_authority  count
1                                საქართველოს მთავრობა    104
2              საქართველოს ეროვნული ბანკის პრეზიდენტი     90
5                       საქართველოს ფინანსთა მინისტრი     29
6   ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის...     20
0                              საქართველოს პარლამენტი     18
16                  საქართველოს ეროვნული ბანკის საბჭო      7
3   სახელმწიფო აუდიტის სამსახურის გენერალური აუდიტორი      5
14                სსიპ დეპოზიტების დაზღვევის სააგენტო      4
7        სახელმწიფო შესყიდვების სააგენტოს თავმჯდომარე      4
18  აჭარის ავტონომიური რესპუბლიკის ფინანსთა და ეკო...      3
4          აფხაზეთის ავტონომიური რესპუბლიკის მინისტრი      2
13  აჭარის ავტონომიური რესპუბლიკის უმაღლესი წარმომ...      2
17                     საქართველოს იუსტიციის მინისტრი      2
10       საქართველოს ფინანსური მონიტორინგის სამსახური      1
8          აფხაზეთის ავტონომიური რესპუბლიკის მთავრობა      1
11                   საქართველოს გენერალური პროკურორი      1
12  აფხაზეთის ავტონომიური რესპუბლიკის უმაღლესი წარ...      1
9   საქართველოს განათლების, მეცნიერებისა და ახალგა...      1
15  სსიპ – სახელმწიფო გრანტის მართვის სააგენტოს თა...      1
19  საქართველოს კონკურენციის ეროვნული სააგენტოს თა...      1
20            აჭარის ავტონომიური რესპუბლიკის მთავრობა      1
21                სსიპ − ანტიკორუფციული ბიუროს უფროსი      1
22  საქართველოს ოკუპირებული ტერიტორიებიდან დევნილთ...      1

In [18]:
from datetime import datetime

bad_dates = []
parsed_dates = []

for d in docs:
    date_string = d.get("signing_date")
    
    try:
        parsed = datetime.strptime(date_string, "%d/%m/%Y")
        parsed_dates.append(parsed)
    except (TypeError, ValueError):
        bad_dates.append({
            "document_id": d["document_id"],
            "signing_date": date_string,
            "title": d["title"],
        })

print("=== DATE SANITY ===")
print(f"Bad/unparseable dates: {len(bad_dates)}")

if bad_dates:
    display(pd.DataFrame(bad_dates))

if parsed_dates:
    print(f"Earliest signing date: {min(parsed_dates).date()}")
    print(f"Latest signing date:   {max(parsed_dates).date()}")

=== DATE SANITY ===
Bad/unparseable dates: 0
Earliest signing date: 2022-12-23
Latest signing date:   2026-09-29

# Random Check

In [19]:
import random

random.seed(42)

sample = random.sample(docs, min(10, len(docs)))

for i, d in enumerate(sample, start=1):
    print("=" * 100)
    print(f"SAMPLE {i}")
    print(f"ID:       {d['document_id']}")
    print(f"Title:    {d['title']}")
    print(f"Type:     {d['document_type']}")
    print(f"Authority:{d['issuing_authority']}")
    print(f"Date:     {d['signing_date']}")
    print(f"Parts:    {d['part_count']}")
    print(f"Chars:    {len(d['text'])}")
    print()
    print(d["text"][:1500])
    print()

====================================================================================================
SAMPLE 1
ID:       6733900
Title:    შპს საქართველოს ფოსტის მიერ საქონლისა და მომსახურების შესყიდვების სპეციალური წესის დამტკიცების შესახებ
Type:     საქართველოს მთავრობის დადგენილება
Authority:საქართველოს მთავრობა
Date:     29/12/2025
Parts:    10
Chars:    32014

შპს საქართველოს ფოსტის მიერ საქონლისა და მომსახურების შესყიდვების სპეციალური წესის დამტკიცების შესახებ

„სახელმწიფო შესყიდვების შესახებ“ საქართველოს კანონის მე-3 მუხლის პირველი პუნქტის „ა.თ“ ქვეპუნქტის შესაბამისად, დამტკიცდეს თანდართული „შპს საქართველოს ფოსტის მიერ საქონლისა და მომსახურების შესყიდვების სპეციალური წესი“.

ეს დადგენილება მოქმედია 2026 წლის 31 დეკემბრის ჩათვლით.

დადგენილება ამოქმედდეს 2026 წლის 1 იანვრიდან.

პრემიერ-მინისტრი ირაკლი კობახიძე

მუხლი 1. ზოგადი დებულებები 1. „შპს საქართველოს ფოსტის მიერ საქონლისა და მომსახურების შესყიდვების სპეციალური წესი“ (შემდგომში – წესი) შემუშავებულია „სახელმწიფო შესყიდვების შესახებ“ საქართველოს კანონის მე-3 მუხლის პირველი პუნქტის „ა.თ“ ქვეპუნქტის შესაბამისად და ადგენს ამ წესით განსაზღვრული საქონლისა და მომსახურების შესყიდვების წესს. 2. ამ წესის მიზანია განსახორციელებელი მომსახურებისა და საქონლის შესყიდვების პროცედურების გამარტივება და შემსყიდველის მიზნების შეუფერხებლად განხორციელების უზრუნველყოფა. მუხლი 2. ტერმინთა განმარტება ამ წესში გამოყენებულ ტერმინებს აქვს შემდეგი მნიშვნელობა: ა) შემსყიდველი – საწარმო, რომელიც თავისი საქმიანობის სპეციფიკასთან დაკავშირებული საქონლის ან მომსახურების შესყიდვისას ხელმძღვანელობს საქართველოს მთავრობის მიერ საქონლის ან მომსახურების შესყიდვისთვის დადგენილი ამ სპეციალური წესით; ბ) შესყიდვა – შემსყიდველის მიერ ამ წესის დანართით განსაზღვრული საქონლისა და მომსახურების შესყიდვა; გ) პირდაპირი შესყიდვა – შესყიდვის საშუალება, რომელიც გამოიყენება ამ წესის მე-4 მუხლით გათვალისწინებულ შემთხვევებში; დ) სახე

====================================================================================================
SAMPLE 2
ID:       6906141
Title:    აგროთანადაფინანსების სახელმწიფო პროგრამის დამტკიცების შესახებ
Type:     საქართველოს მთავრობის დადგენილება
Authority:საქართველოს მთავრობა
Date:     24/06/2026
Parts:    12
Chars:    6013

აგროთანადაფინანსების სახელმწიფო პროგრამის დამტკიცების შესახებ

„საქართველოს მთავრობის სტრუქტურის, უფლებამოსილებისა და საქმიანობის წესის შესახებ“ საქართველოს კანონის მე-5 მუხლის „ვ“ ქვეპუნქტის შესაბამისად, დამტკიცდეს თანდართული „აგროთანადაფინანსების სახელმწიფო პროგრამა“.

ამ დადგენილების პირველი მუხლით დამტკიცებული „აგროთანადაფინანსების სახელმწიფო პროგრამის“ ფარგლებში: 1. მონაწილეობას შეძლებენ ის პოტენციური ბენეფიციარები, რომლებსაც არ აქვთ ა(ა)იპ − სოფლის განვითარების სააგენტოს პროექტების/პროგრამების ფარგლებში მიმდინარე სახელშეკრულებო დარღვევა ან/და სასამართლო დავა. 2. ის ბენეფიციარები, ვისთანაც გაფორმდება თანადაფინანსების ხელშეკრულება, თანადაფინანსებას მიიღებენ იმ შემთხვევაში, თუ ამ დადგენილების ამოქმედების შემდეგ ა(ა)იპ − სოფლის განვითარების სააგენტოს პროექტების/პროგრამების ფარგლებში არ ექნებათ მიმდინარე სახელშეკრულებო დარღვევა ან/და სასამართლო დავა. 3. პოტენციური ბენეფიციარის/ბენეფიციარის პროექტის განხორციელების თანხას არ შეიძლება, წარმოადგენდეს ამ დადგენილების ამოქმედებამდე „შეღავათიანი აგროკრედიტის პროექტისა და გადამამუშავებელი და შემნახველი საწარმოების თანადაფინანსების პროექტის დამტკიცების შესახებ“ საქართველოს მთავრობის 2014 წლის 27 იანვრის №139 განკარგულებით დამტკიცებული „შეღავათიანი აგროკრედიტის პროექტის“ ფარგლებში გაცემული სესხი.

„აგროთანადაფინანსების სახელმწიფო პროგრამის“ დაფინანსება განხორციელდეს შესაბამისი წლის საქართველოს სახელმწიფო ბიუჯეტის შესახებ საქართველოს კანონით გათვალისწინებული შესაბამისი პროგრამული კოდის ასიგნებებიდან.

„დანერგე მომავალი“ სახელმწიფო პროგ

====================================================================================================
SAMPLE 3
ID:       6234456
Title:    აქტივების მმართველი კომპანიების ფულის გათეთრებისა და ტერორიზმის დაფინანსების რისკის ზედამხედველობის ანგარიშგების შევსებისა და ინფორმაციის წარდგენის წესის დამტკიცების თაობაზე
Type:     საქართველოს ეროვნული ბანკის პრეზიდენტის ბრძანება
Authority:საქართველოს ეროვნული ბანკის პრეზიდენტი
Date:     26/07/2024
Parts:    10
Chars:    40364

აქტივების მმართველი კომპანიების ფულის გათეთრებისა და ტერორიზმის დაფინანსების რისკის ზედამხედველობის ანგარიშგების შევსებისა და ინფორმაციის წარდგენის წესის დამტკიცების თაობაზე

„საქართველოს ეროვნული ბანკის შესახებ“ საქართველოს ორგანული კანონის მე-15 მუხლის პირველი პუნქტის „ზ“ ქვეპუნქტის, 48-ე მუხლის მე-3 პუნქტის, 52 4 მუხლის „ბ“ და „ე“ ქვეპუნქტების და „ფულის გათეთრებისა და ტერორიზმის დაფინანსების აღკვეთის ხელშეწყობის შესახებ“ საქართველოს კანონის მე-4 მუხლის „გ“ ქვეპუნქტისა და ამავე კანონის 38-ე მუხლის მოთხოვნათა შესაბამისად, ვბრძანებ:

დამტკიცდეს „აქტივების მმართველი კომპანიების ფულის გათეთრებისა და ტერორიზმის დაფინანსების რისკის ზედამხედველობის ანგარიშგების შევსებისა და ინფორმაციის წარდგენის წესი“ თანდართულ დანართებთან ერთად.

აქტივების მმართველმა კომპანიებმა ამ ბრძანებით დამტკიცებული რისკის ზედამხედველობის პირველი ანგარიშგების წარდგენა უზრუნველყონ 2024 წლის 1 იანვრიდან 2024 წლის 30 ივნისის ჩათვლით პერიოდზე, არაუგვიანეს 2024 წლის 31 აგვისტოსი.

ეს ბრძანება ამოქმედდეს გამოქვეყნებისთანავე.

საქართველოს ეროვნული ბანკის პრეზიდენტის მოვალეობის შემსრულებელი ნათელა თურნავა

მუხლი 1. წესის მიზანი და მოქმედების სფერო 1. „აქტივების მმართველი კომპანიების ფულის გათეთრებისა და ტერორიზმის დაფინანსების რისკის ზედამხედველობის ანგარიშგების შევსებისა და ინფორმაციის წარდგენის წესი“ (შემდგომში – წესი) განსაზღვრავს ამ წესის №1 დანართით გათვალისწინებული „აქტივების მმართველი კომპანიების ფულის გათეთრებისა და ტერორიზმის დაფინანსების რისკის ზედამხედველობის ანგარიშგების“ (შემდგომში – ანგარიშგება) ცალკეუ

====================================================================================================
SAMPLE 4
ID:       6351150
Title:    ლარის ბანკნოტებისა და მონეტების განადგურების წესის დამტკიცების შესახებ
Type:     საქართველოს ეროვნული ბანკის საბჭოს დადგენილება
Authority:საქართველოს ეროვნული ბანკის საბჭო
Date:     25/12/2024
Parts:    10
Chars:    25562

ლარის ბანკნოტებისა და მონეტების განადგურების წესის დამტკიცების შესახებ

„ საქართველოს ეროვნული ბანკის შესახებ “ საქართველოს ორგანული კანონის მე -9 მუხლის „ ვ “ ქვეპუნქტის, ამავე ორგანული კანონის 36- ე მუხლის მე -3 პუნქტის ა და „ ნორმატიული აქტების შესახებ “ საქართველოს ორგანული კანონის 25- ე მუხლის პირველი პუნქტის „ ბ “ ქვეპუნქტის საფუძველზე , საქართველოს ეროვნული ბანკის საბჭო ადგენს :

დამტკიცდეს ლარის ბანკნოტებისა და მონეტების განადგურების წესი თანდართული რედაქციით .

ძალადაკარგულად გამოცხადდეს „ ლარის ბანკნოტებისა და მონეტების განადგურების წესის დამტკიცების შესახებ “ საქართველოს ეროვნული ბანკის საბჭოს 2018 წლის 28 მაისის №5 დადგენილება .

ეს დადგენილება ამოქმედდეს გამოქვეყნებისთანავე .

საქართველოს ეროვნული ბანკის საბჭოს თავმჯდომარის მოვალეობის შემსრულებელი ნათელა თურნავა

ლარის ბანკნოტებისა და მონეტების განადგურების წესი მუხლი 1. ზოგადი დებულებები 1. ლარის ბანკნოტებისა და მონეტების განადგურების წესი (შემდგომში – წესი) არეგულირებს საქართველოს ეროვნული ბანკის ( შემდგომში – ეროვნული ბანკი ) მიერ მიმოქცევისთვის უვარგისი ლარის ბანკნოტებისა და მონეტების გადათვლა – განადგურების ოპერაციების წარმოების საკითხებს . 2. ამ წესის მიზნებისთვის მიმოქცევისთვის უვარგის ლარის ბანკოტებსა და მონეტებს ( შემდგომში – ბანკნოტები და მონეტები ) განეკუთვნება : ა ) ეროვნული ბანკის საბჭოს მიერ დადგენილი დონის შესაბამისი ფიზიკური ცვეთის ან / და სხვა დაზიანების მქონე ბანკნოტები და მონეტები ; ბ ) ქარხნული წუნის მქონე ბანკნოტები და მონეტები ; გ ) ეროვნული ბანკის საბჭოს მიერ მიღებული გადაწყვეტილების საფუძვ

====================================================================================================
SAMPLE 5
ID:       6425955
Title:    ხარისხის მართვის საერთაშორისო სტანდარტის, აუდიტის, მიმოხილვის, სხვა მარწმუნებელი და დაკავშირებული მომსახურების საერთაშორისო სტანდარტებისა და პროფესიონალი ბუღალტრების ეთიკის კოდექსის ქართულ ენაზე სამოქმედოდ შემოღების შესახებ
Type:     ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის ზედამხედველობის სამსახურის უფროსის ბრძანება
Authority:ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის ზედამხედველობის სამსახურის უფროსი
Date:     25/02/2025
Parts:    5
Chars:    1705

ხარისხის მართვის საერთაშორისო სტანდარტის, აუდიტის, მიმოხილვის, სხვა მარწმუნებელი და დაკავშირებული მომსახურების საერთაშორისო სტანდარტებისა და პროფესიონალი ბუღალტრების ეთიკის კოდექსის ქართულ ენაზე სამოქმედოდ შემოღების შესახებ

„ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის შესახებ“ საქართველოს კანონის მე-14 მუხლის მე-3 პუნქტის, მე-16 მუხლის მე-2 პუნქტის, მე-19 მუხლის მე-3 პუნქტის და მე-20 მუხლის მე-3 პუნქტის „ა“ქვეპუნქტის საფუძველზე, ვბრძანებ:

1. ქართულ ენაზე სამოქმედოდ შემოღებულ იქნეს აუდიტისა და მარწმუნებელი მომსახურების საერთაშორისო საბჭოს (IAASB) მიერ მიღებული და გამოცემული ხარისხის მართვის, აუდიტის, მიმოხილვის, სხვა მარწმუნებელი და დაკავშირებული მომსახურების საერთაშორისო დოკუმენტების ცნობარით (2023-2024 წლის გამოცემა) გათვალისწინებული: ა) ხარისხის მართვის საერთაშორისო სტანდარტი (შემდგომ – სტანდარტი); ბ) აუდიტის, მიმოხილვის, სხვა მარწმუნებელი და დაკავშირებული მომსახურების საერთაშორისო სტანდარტები (შემდგომ – სტანდარტი). 2. ქართულ ენაზე სამოქმედოდ შემოღებულ იქნეს ბუღალტერთა საერთაშორისო ფედერაციის (IFAC) მიერ დადგენილი (2024 წლის გამოცემა) ეთიკის საერთაშორისო კოდექსის სახელმძღვანელო პროფესიონალი ბუღალტრებისთვის (IESBA Code) (შემდგომ – პროფესიული ეთიკის კოდექსი). 3. ამ ბრძანებით გათვალისწინებული სტანდარტები და პროფესიული ეთიკის კოდექსი განთავსდეს ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის ზედამხედველობის სამსახურის (შემდგომ – სამსახური) ვებგვერდზე (www.saras.gov.ge). 4. სამსახური უზრუნველყოფს ამ ბრძანებით სამოქმედოდ შემოღებული სტანდარტებისა და პროფესიული ეთიკის კოდექსის

====================================================================================================
SAMPLE 6
ID:       6720130
Title:    სს „საქართველოს ნავთობისა და გაზის კორპორაციის“ მიერ საქონლისა და მომსახურების შესყიდვების სპეციალური წესის დამტკიცების შესახებ
Type:     საქართველოს მთავრობის დადგენილება
Authority:საქართველოს მთავრობა
Date:     24/12/2025
Parts:    10
Chars:    33681

სს „საქართველოს ნავთობისა და გაზის კორპორაციის“ მიერ საქონლისა და მომსახურების შესყიდვების სპეციალური წესის დამტკიცების შესახებ

„სახელმწიფო შესყიდვების შესახებ“ საქართველოს კანონის მე-3 მუხლის პირველი პუნქტის „ა.თ“ ქვეპუნქტის შესაბამისად, დამტკიცდეს თანდართული „სს „საქართველოს ნავთობისა და გაზის კორპორაციის“ მიერ საქონლისა და მომსახურების შესყიდვების სპეციალური წესი“.

დადგენილების მოქმედების ვადად განისაზღვროს ამოქმედებიდან 1 (ერთი) წელი.

დადგენილება ამოქმედდეს 2026 წლის 1 იანვრიდან.

პრემიერ-მინისტრი ირაკლი კობახიძე

მუხლი 1. ზოგადი დებულებები 1. სს „საქართველოს ნავთობისა და გაზის კორპორაციის“ მიერ საქონლისა და მომსახურების შესყიდვების სპეციალური წესი (შემდგომში – წესი) შემუშავებულია „სახელმწიფო შესყიდვების შესახებ“ საქართველოს კანონის მე-3 მუხლის პირველი პუნქტის „ა.თ“ ქვეპუნქტის შესაბამისად და ადგენს სს „საქართველოს ნავთობისა და გაზის კორპორაციის“ (შემდგომში – საწარმო) მიერ ამ წესით განსაზღვრული საქონლისა (დანართი №1) და მომსახურების (დანართი №2) შესყიდვების წესს. 2. ამ წესის მიზანია ამავე წესის №1 და №2 დანართებით განსაზღვრული მომსახურებისა და საქონლის შესყიდვების პროცედურების გამარტივება და შემსყიდველის მიზნების შეუფერხებლად განხორციელების უზრუნველყოფა. მუხლი 2. ტერმინთა განმარტება ამ წესში გამოყენებულ ტერმინებს აქვს შემდეგი მნიშვნელობა: ა) შემსყიდველი – საწარმო, რომელიც თავისი საქმიანობის სპეციფიკასთან დაკავშირებული საქონლის ან მომსახურების შესყიდვისას ხელმძღვანელობს საქართველოს მთავრობის მიერ საქონლის ან მომსახურების შესყიდვისთვის დადგენილი ამ სპეციალური წესით; ბ) შე

====================================================================================================
SAMPLE 7
ID:       6747511
Title:    სს საქართველოს ენერგეტიკის განვითარების ფონდისათვის საქონლისა და მომსახურების შესყიდვების სპეციალური წესის დამტკიცების შესახებ
Type:     საქართველოს მთავრობის დადგენილება
Authority:საქართველოს მთავრობა
Date:     31/12/2025
Parts:    10
Chars:    30326

სს საქართველოს ენერგეტიკის განვითარების ფონდისათვის საქონლისა და მომსახურების შესყიდვების სპეციალური წესის დამტკიცების შესახებ

„სახელმწიფო შესყიდვების შესახებ“ საქართველოს კანონის მე-3 მუხლის პირველი პუნქტის „ა.თ“ ქვეპუნქტის შესაბამისად, დამტკიცდეს თანდართული „სს საქართველოს ენერგეტიკის განვითარების ფონდისათვის საქონლისა და მომსახურების შესყიდვების სპეციალური წესი“.

დადგენილების მოქმედების ვადად განისაზღვროს 2026 წლის 1 იანვრიდან 2026 წლის 31 დეკემბრის ჩათვლით პერიოდი.

დადგენილება ამოქმედდეს 2026 წლის 1 იანვრიდან.

პრემიერ-მინისტრი ირაკლი კობახიძე

მუხლი 1. ზოგადი დებულებები 1. „სს საქართველოს ენერგეტიკის განვითარების ფონდისათვის საქონლისა და მომსახურების შესყიდვების სპეციალური წესი“ (შემდგომში – წესი) შემუშავებულია „სახელმწიფო შესყიდვების შესახებ“ საქართველოს კანონის მე-3 მუხლის პირველი პუნქტის „ა.თ“ ქვეპუნქტის შესაბამისად და ადგენს ამ წესით განსაზღვრული საქონლისა და მომსახურების შესყიდვების წესს. 2. ამ წესის მიზანია განსახორციელებელი მომსახურებისა და საქონლის შესყიდვების პროცედურების გამარტივება და შემსყიდველის მიზნების შეუფერხებლად განხორციელების უზრუნველყოფა. მუხლი 2. ტერმინთა განმარტება ამ წესში გამოყენებულ ტერმინებს აქვს შემდეგი მნიშვნელობა: ა) შემსყიდველი – სს საქართველოს ენერგეტიკის განვითარების ფონდი; ბ) შესყიდვა – სს საქართველოს ენერგეტიკის განვითარების ფონდის მიერ იმ საქონლისა და მომსახურების შესყიდვა, რომლებიც მოცემულია ამ წესის №1 და №2 დანართებში; გ) პირდაპირი შესყიდვა – შესყიდვის საშუალება, რომელიც გამოიყენება ამ წესის მე-4 მუხლით გათვალისწინებულ შემთხვევებშ

====================================================================================================
SAMPLE 8
ID:       5759986
Title:    საქართველოს ფინანსთა სამინისტროს მმართველობის სფეროში შემავალი საჯარო სამართლის იურიდიული პირის – შემოსავლების სამსახურის საბაჟო დეპარტამენტის თანამშრომელთა და ამავე დეპარტამენტის საქმიანობაზე ზედამხედველი შემოსავლების სამსახურის უფროსის მოადგილის ფორმის ტანსაცმლის ნიმუშების, სახელმწიფო სპეციალური წოდების განმასხვავებელი ნიშნების აღწერილობისა და მათი ტარების წესის დამტკიცების შესახებ
Type:     საქართველოს მთავრობის დადგენილება
Authority:საქართველოს მთავრობა
Date:     27/03/2023
Parts:    5
Chars:    1010

საქართველოს ფინანსთა სამინისტროს მმართველობის სფეროში შემავალი საჯარო სამართლის იურიდიული პირის – შემოსავლების სამსახურის საბაჟო დეპარტამენტის თანამშრომელთა და ამავე დეპარტამენტის საქმიანობაზე ზედამხედველი შემოსავლების სამსახურის უფროსის მოადგილის ფორმის ტანსაცმლის ნიმუშების, სახელმწიფო სპეციალური წოდების განმასხვავებელი ნიშნების აღწერილობისა და მათი ტარების წესის დამტკიცების შესახებ

„სახელმწიფო სპეციალური წოდებების შესახებ“ საქართველოს კანონის მე-10 მუხლის მე-2 და 2 1 პუნქტების შესაბამისად, დამტკიცდეს თანდართული „საქართველოს ფინანსთა სამინისტროს მმართველობის სფეროში შემავალი საჯარო სამართლის იურიდიული პირის – შემოსავლების სამსახურის საბაჟო დეპარტამენტის თანამშრომელთა და ამავე დეპარტამენტის საქმიანობაზე ზედამხედველი შემოსავლების სამსახურის უფროსის მოადგილის ფორმის ტანსაცმლის ნიმუშები, სახელმწიფო სპეციალური წოდების განმასხვავებელი ნიშნების აღწერილობა და მათი ტარების წესი“ დანართებთან ერთად (დანართი №1, დანართი №2).

დადგენილება ამოქმედდეს გამოქვეყნებისთანავე.

პრემიერ-მინისტრი ირაკლი ღარიბაშვილი

====================================================================================================
SAMPLE 9
ID:       6793594
Title:    ანგარიშგების ვებგვერდზე გამოქვეყნებული ანგარიშგებების საერთაშორისო სტანდარტებთან შესაბამისობის მიმოხილვის წესის შესახებ
Type:     ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის ზედამხედველობის სამსახურის უფროსის ბრძანება
Authority:ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის ზედამხედველობის სამსახურის უფროსი
Date:     24/02/2026
Parts:    45
Chars:    10367

ანგარიშგების ვებგვერდზე გამოქვეყნებული ანგარიშგებების საერთაშორისო სტანდარტებთან შესაბამისობის მიმოხილვის წესის შესახებ

„ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის შესახებ“ საქართველოს კანონის მე-9 მუხლის 3 1 პუნქტისა და მე-20 მუხლის მე-3 პუნქტის „ნ“ ქვეპუნქტის შესაბამისად, ვბრძანებ:

დამტკიცდეს „ანგარიშგების ვებგვერდზე გამოქვეყნებული ანგარიშგებების საერთაშორისო სტანდარტებთან შესაბამისობის მიმოხილვის წესი“, დანართის შესაბამისად.

ეს ბრძანება ამოქმედდეს გამოქვეყნებისთანავე.

ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის ზედამხედველობის სამსახურის უფროსი დავით მჭედლიძე

ანგარიშგების ვებგვერდზე გამოქვეყნებული ანგარიშგებების საერთაშორისო სტანდარტებთან შესაბამისობის მიმოხილვის წესი

1. ეს წესი განსაზღვრავს საქართველოში ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის ზედამხედველობის სამსახურის (შემდგომ – სამსახური) მიერ ანგარიშგების ვებგვერდზე გამოქვეყნებული ინდივიდუალური/კონსოლიდირებული ანგარიშგებების საერთაშორისო სტანდარტებთან შესაბამისობის მიმოხილვის წესს, რისკის მართვის, მიმოხილვისა და სამართალდარღვევის იდენტიფიცირების მიზნებისთვის ადმინისტრაციული წარმოების წარმართვის და შეუსაბამობების გამოვლენის პროცედურებს.

2. მიმოხილვას ექვემდებარება, მიმოხილვასთან დაკავშირებული ადმინისტრაციული წარმოების დაწყებამდე წარდგენილი და გამოქვეყნებული, უახლესი საანგარიშგებო პერიოდის ანგარიშგება.

3. ამ წესის მიზანია: ა) ანგარიშგების საერთაშორისო სტანდარტებთან შესაბამისობის შეფასების სამართლებრივი პროცედურის დადგენა; ბ) მიმოხილვის შედეგად ანგარიშგების ხარისხის ზრდა, საერთაშორისო სტანდარტებთან შ

====================================================================================================
SAMPLE 10
ID:       5888234
Title:    საქართველოს ეროვნული ბანკის ზედამხედველობას დაქვემდებარებული ანგარიშვალდებული პირების მიერ სანქციათა რეჟიმების შესრულების წესის დამტკიცების თაობაზე
Type:     საქართველოს ეროვნული ბანკის პრეზიდენტის ბრძანება
Authority:საქართველოს ეროვნული ბანკის პრეზიდენტი
Date:     04/08/2023
Parts:    14
Chars:    4375

საქართველოს ეროვნული ბანკის ზედამხედველობას დაქვემდებარებული ანგარიშვალდებული პირების მიერ სანქციათა რეჟიმების შესრულების წესის დამტკიცების თაობაზე

„საქართველოს ეროვნული ბანკის შესახებ“ საქართველოს ორგანული კანონის მე-15 მუხლის პირველი პუნქტის „ზ“ ქვეპუნქტის, 47-ე მუხლისა და 48-ე მუხლის მე-3 პუნქტის საფუძველზე, ვბრძანებ:

დამტკიცდეს საქართველოს ეროვნული ბანკის ზედამხედველობას დაქვემდებარებული ანგარიშვალდებული პირების მიერ სანქციათა რეჟიმების შესრულების წესი თანდართულ დანართებთან ერთად.

ეს ბრძანება ამოქმედდეს გამოქვეყნებისთანავე.

საქართველოს ეროვნული ბანკის პირველი ვიცე-პრეზიდენტი/ საქართველოს ეროვნული ბანკის პრეზიდენტის მოვალეობის შემსრულებელი ნათელა თურნავა

საქართველოს ეროვნული ბანკის ზედამხედველობას დაქვემდებარებული ანგარიშვალდებული პირების (შემდგომში – „ანგარიშვალდებული პირები“) მიერ სანქციათა რეჟიმების შესრულების წესი (შემდგომში – „წესი“) განსაზღვრავს ანგარიშვალდებული პირების ვალდებულებას შეასრულონ რუსეთის ფედერაციის და ბელარუსის რესპუბლიკის მიმართ ამერიკის შეერთებული შტატების (შემდგომში – „აშშ“), ევროკავშირისა და დიდი ბრიტანეთის მიერ დაწესებული სანქციათა რეჟიმების მოთხოვნები (შემდგომში – „რუსეთისა და ბელარუსის მიმართ დაწესებული სანქციები“) და ამ მიმართულებით შეიმუშაონ/დანერგონ ეფექტიანი შიდა კონტროლის მექანიზმები.

ანგარიშვალდებული პირები ვალდებულნი არიან დაიცვან უკრაინაში განვითარებული მოვლენების გამო რუსეთისა და ბელარუსის მიმართ დაწესებული სანქციათა მოთხოვნებით, რაც მოიცავს: ა) აშშ-ს მიერ დაწესებულ სანქციებს; ბ) ევროკავშირის მიერ დაწესებულ სანქციებს; გ) დიდი ბრიტან

In [20]:
enclosure_doc_ids = sorted({
    row["document_id"]
    for row in enclosure_parts
})

print(f"Documents with enclosures: {len(enclosure_doc_ids)}")

for document_id in enclosure_doc_ids[:5]:
    d = next(x for x in docs if x["document_id"] == document_id)
    
    print("=" * 100)
    print(d["document_id"])
    print(d["title"])
    
    for part in d["parts"]:
        print(
            f"\nTYPE={part['type']} | "
            f"ENCLOSURE={part['enclosure']} | "
            f"STRUCTURE={' > '.join(part['structure'])}"
        )
        print(part["text"][:500])

Documents with enclosures: 195
====================================================================================================
5662765
საქართველოს გარემოს დაცვისა და სოფლის მეურნეობის სამინისტროს სისტემის უფლებამოსილი ორგანოს მიერ ცხოველის ან/და მცენარის ახალი ჯიშის განსხვავებულობაზე, ერთგვაროვნებასა და სტაბილურობაზე გამოცდის ჩატარების საფასურის ოდენობის დამტკიცების შესახებ

TYPE=HEADER | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > HEADER:1
საქართველოს გარემოს დაცვისა და სოფლის მეურნეობის სამინისტროს სისტემის უფლებამოსილი ორგანოს მიერ ცხოველის ან/და მცენარის ახალი ჯიშის განსხვავებულობაზე, ერთგვაროვნებასა და სტაბილურობაზე გამოცდის ჩატარების საფასურის ოდენობის დამტკიცების შესახებ

TYPE=PREAMBLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > PREAMBLE:1


TYPE=ARTICLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > ARTICLE:1
„ცხოველთა და მცენარეთა ახალი ჯიშების შესახებ“ საქართველოს კანონის 47-ე მუხლის მე-6 პუნქტის „ბ“ ქვეპუნქტის შესაბამისად, დამტკიცდეს თანდართული „საქართველოს გარემოს დაცვისა და სოფლის მეურნეობის სამინისტროს სისტემის უფლებამოსილი ორგანოს მიერ ცხოველის ან/და მცენარის ახალი ჯიშის განსხვავებულობაზე, ერთგვაროვნებასა და სტაბილურობაზე გამოცდის ჩატარების საფასურის ოდენობა“.

TYPE=ARTICLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > ARTICLE:2
დადგენილება ამოქმედდეს გამოქვეყნებისთანავე.

TYPE=FOOTER | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > FOOTER:1
პრემიერ-მინისტრი ირაკლი ღარიბაშვილი

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > HEADER:1


TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > PREAMBLE:1


TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > POINT:1
№ სამუშაოს დასახელება საზომი ერთეული (ერთი ჯიში/ერთი განაცხადი) საფასური ლარში, დღგ-ის ჩათვლით 1 DUS ტესტის ორგანიზება/ჩატარება მარცვლეული 650 ბაღჩეული 550

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > FOOTER:1

====================================================================================================
5679194
ფინანსური ინსტრუმენტების რისკის კატეგორიებისა და მოსალოდნელი საკრედიტო ზარალის განსაზღვრის წესის დამტკიცების თაობაზე

TYPE=HEADER | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > HEADER:1
ფინანსური ინსტრუმენტების რისკის კატეგორიებისა და მოსალოდნელი საკრედიტო ზარალის განსაზღვრის წესის დამტკიცების თაობაზე

TYPE=PREAMBLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > PREAMBLE:1
„საქართველოს ეროვნული ბანკის შესახებ“ საქართველოს ორგანული კანონის მე-15 მუხლის პირველი პუნქტის „ზ“ ქვეპუნქტის, ამავე ორგანული კანონის 48-ე მუხლის მე-3 პუნქტისა და „კომერციული ბანკების საქმიანობის შესახებ“ საქართველოს კანონის 21-ე მუხლის საფუძველზე, ვბრძანებ:

TYPE=ARTICLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > ARTICLE:1
დამტკიცდეს ფინანსური ინსტრუმენტების რისკის კატეგორიებისა და მოსალოდნელი საკრედიტო ზარალის განსაზღვრის წესი თანდართული რედაქციით.

TYPE=ARTICLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > ARTICLE:2
კომერციული ბანკი ვალდებულია, „საქართველოს საბანკო დაწესებულებებისათვის ბუღალტრული აღრიცხვის ანგარიშთა გეგმის და ანგარიშთა გეგმის გამოყენების ინსტრუქციისა“ (ე.წ. ადგილობრივი GAAP) და ფინანსური ანგარიშგების საერთაშორისო სტანდარტების მიხედვით პარალელური ანგარიშგების პერიოდში, საქართველოს ეროვნული ბანკის მიერ სხვა გადაწყვეტილების მიღებამდე, საზედამხედველო ანგარიშგების მიზნებისთვის აგრეთვე იმოქმედოს „კომერციული ბანკების მიერ აქტივების კლასიფიკაციისა და შესაძლო დანაკარგების რეზერვების შექმნისა და გამო

TYPE=ARTICLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > ARTICLE:3
ეს ბრძანება ამოქმედდეს 2023 წლის 1 იანვრიდან.

TYPE=FOOTER | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > FOOTER:1
ეროვნული ბანკის პრეზიდენტი კობა გვენეტაძე

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > HEADER:1


TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > PREAMBLE:1


TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:1
1. ფინანსური ინსტრუმენტების რისკის კატეგორიებისა და მოსალოდნელი საკრედიტო ზარალის განსაზღვრის წესის (შემდგომში – წესი) მიზანია, ფინანსურ ანგარიშგებაში კომერციული ბანკის ფინანსური მდგომარეობის შესახებ ზუსტი, სრული და მიმდინარე ინფორმაციის ასახვა ფინანსური ანგარიშგების საერთაშორისო სტანდარტი 9-ის (შემდგომში – ფასს 9) მიხედვით ფინანსური ინსტრუმენტების მოსალოდნელი საკრედიტო ზარალისა და ხარისხთან დაკავშირებით, რომელიც სასარგებლო ინფორმაციას წარმოადგენს ფინანსური ანგარიშგების მომხმარებლებისათვის კომერ

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:2
1. ამ წესში გამოყენებულ ტერმინებს აქვს შემდეგი მნიშვნელობა: ა) ფინანსური ინსტრუმენტი – ბუღალტრული აღრიცხვის საერთაშორისო სტანდარტი (ბასს) 32-ის მიხედვით განსაზღვრული ფინანსური ინსტრუმენტები; ბ) მაღალი საკრედიტო რისკის ფინანსური ინსტრუმენტი – პირველი დონის საკრედიტო რისკის კატეგორიის პოტენციურად სუსტი ფინანსური ინსტრუმენტი, როდესაც მსესხებლის ფინანსური მდგომარეობა და გადახდის უნარი არ არის სტაბილური. ფინანსური ინსტრუმენტის გაცემისთანავე არსებობს ისეთი ნაკლოვანებები და ნეგატიური ტენდენციები, რომლი

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:3
1. ფინანსური ინსტრუმენტის საკრედიტო რისკის კლასიფიკაცია წარმოებს სამი კატეგორიის მიხედვით: ა) პირველი დონის საკრედიტო რისკის ფინანსური ინსტრუმენტები; ბ) მე-2 დონის საკრედიტო რისკის ფინანსური ინსტრუმენტები; გ) მე-3 დონის საკრედიტო რისკის ფინანსური ინსტრუმენტები. 2. საკრედიტო რისკის კატეგორიის დადგენა/მინიჭებისას: ა) კომერციულმა ბანკმა ამომწურავად უნდა მოიძიოს ინფორმაცია, რომელიც მნიშვნელოვანია საკრედიტო რისკის კატეგორიის დადგენისას როგორც ფინანსური ინსტრუმენტის თავდაპირველი გაცემისას, ასევე ამ ფი

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:4
1. პირველი დონის საკრედიტო რისკის კატეგორიაში კლასიფიცირდება ის ფინანსური ინსტრუმენტები, რომლებიც აკმაყოფილებენ ერთ ან რამდენიმე შემდეგ კრიტერიუმს: ა) არ მიეკუთვნება მე-2 და მე-3 დონის საკრედიტო რისკის კატეგორიებს; ბ) ფინანსური ინსტრუმენტი არ უნდა იყოს 30 დღეზე მეტი პერიოდით ვადაგადაცილებული; გ) ფინანსური ინსტრუმენტის ხელშეკრულებით გათვალისწინებული ნებისმიერი პირობის ცვლილება, რომელიც არ არის განპირობებული მსესხებლის ფინანსური პრობლემებით. 2. ფინანსური ინსტრუმენტის პირველი დონის საკრედიტო რისკის

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:5
1. ფინანსური ინსტრუმენტი კლასიფიცირდება მე-2 დონის საკრედიტო რისკის კატეგორიად, თუ ის არ არის გაუფასურებული და დაკმაყოფილებულია ერთ-ერთი შემდეგი კრიტერიუმები: ა) ფინანსური ინსტრუმენტის საკრედიტო რისკი მნიშვნელოვნად გაიზარდა მისი ფასს-ის მიხედვით თავდაპირველი აღიარების შემდგომ; ბ) ფიქსირდება 30 დღეზე მეტი პერიოდით ვადაგადაცილება; გ) განხორციელდა ფინანსური ინსტრუმენტის რესტრუქტურიზაცია. 2. ფინანსური ინსტრუმენტის კლასიფიკაცია მე-2 დონის საკრედიტო რისკის კატეგორიად, ასევე უნდა ემყარებოდეს მაკროეკონო

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:6
1. მე-3 დონის საკრედიტო რისკის კატეგორიას მიეკუთვნება გაუფასურებული ფინანსური ინსტრუმენტები. 2. ფინანსური ინსტრუმენტი გაუფასურებულია, თუ ის აკმაყოფილებს ერთ ან რამდენიმე შემდეგ კრიტერიუმს: ა) მსესხებელს აქვს ისეთი ფინანსური პრობლემები, რომელიც საფრთხეს უქმნის ვალდებულების შესრულებას ან საეჭვოს ხდის მთლიან გადახდას; ბ) ფინანსური ინსტრუმენტის გადახდის ძირითადი წყაროები, მათ შორის, კაპიტალი, მოგება ან/და ფულადი სახსრების გენერირების უნარი, არ არის საკმარისი ვალდებულების შესასრულებლად. შესაბამისად,

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:7
1. კომერციულმა ბანკმა ფინანსური ინსტრუმენტს რესტრუქტურიზებული ფინანსური ინსტრუმენტის სტატუსი უნდა მიანიჭოს შემდეგი ფაქტორების გათვალისწინებით: ა) ფინანსური ინსტრუმენტის განახლების ან მისი დაფარვის ვადის გაგრძელების რაოდენობა; ბ) ფინანსური ინსტრუმენტის საერთო ვადის ცვლილება მის თავდაპირველ ვადასთან შედარებით; გ) ფინანსური ინსტრუმენტის პროცენტის დაფარვის ვადების ცვლილება თავდაპირველ ვადებთან შედარებით; დ) ფინანსური ინსტრუმენტის გაცემის თაობაზე ხელშეკრულების პირობების კონკრეტული ცვლილებები და ამ ცვ

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:8
1. ფინანსური ინსტრუმენტის ნებისმიერი სახის რეკლასიფიკაცია (კატეგორიის გაუმჯობესება) უნდა ეფუძნებოდეს ფინანსურ ანალიზს, სრულყოფილად უნდა იყოს დოკუმენტირებული და ხელმისაწვდომი ეროვნული ბანკისთვის. 2. ფინანსური ინსტრუმენტის რეკლასიფიკაცია მე-2 დონის საკრედიტო რისკის კატეგორიიდან პირველი დონის საკრედიტო რისკის კატეგორიაში შესაძლებელია, თუ განხორციელდა მსესხებლის ფინანსური ანალიზი, ფინანსური ინსტრუმენტი სრულად და უპირობოდ აკმაყოფილებს პირველი დონის საკრედიტო რისკის კატეგორიის პირობებს და განხორციელებ

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:9
1. მსესხებლის საკრედიტო რისკის კატეგორიის ინდივიდუალურად განსაზღვრის მატერიალურობის დადგენისას, კომერციულმა ბანკმა უნდა გაითვალისწინოს არამარტო მოცემული ფინანსური ინსტრუმენტის, არამედ, მსესხებელთან დაკავშირებული ყველა ფინანსური ინსტრუმენტების კუმულატიური მოცულობა. თუ მსესხებლის ჯამური ვალდებულებების მოცულობა მატერიალურია ამ მუხლის მე-2 პუნქტის მიხედვით, მაშინ თითოეული მსესხებელი უნდა შეფასდეს ინდივიდუალურად. 2. მსესხებელი საკრედიტო რისკის კატეგორიის განსაზღვრის მიზნით უნდა შეფასდეს ინდივიდუალურა

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:10
1. მონაცემების ხარისხი უნდა შეესაბამებოდეს საქართველოს ეროვნული ბანკის პრეზიდენტის 2020 წლის 17 აგვისტოს №151/04 ბრძანებით დამტკიცებული „მონაცემებზე დაფუძნებული სტატისტიკური, ხელოვნური ინტელექტის და მანქანური სწავლების მოდელების რისკების მართვის დებულებით“ განსაზღვრულ პრინციპებსა და მოთხოვნებს. 2. კომერციულმა ბანკმა მოსალოდნელი საკრედიტო ზარალის შეფასების მოდელის განვითარების, ტესტირებისა და დანერგვისათვის უნდა უზრუნველყოს ყველა საჭირო მონაცემის მოპოვება აუცილებელი დეტალიზაციით, მაღალი ხარისხით.

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:11
1. მაკროეკონომიკური ფაქტორების გათვალისწინება უნდა მოხდეს წინასწარ განსაზღვრული საპროგნოზო პერიოდის მანძილზე, რომელიც უნდა იყოს არაუმცირეს სამი წლისა. აღნიშნული პერიოდის შემცირება შესაძლებელია მხოლოდ სათანადო დასაბუთების შემთხვევაში. 2. დეტალური საპროგნოზო პერიოდის მიღმა პროგნოზის გაკეთებისას კომერციულ ბანკს შეუძლია იხელმძღვანელოს გრძელვადიან ისტორიულ საშუალო ზარალზე დაყრდნობით. გრძელვადიანი ისტორიული საშუალო ზარალის გაანგარიშებისას გამოყენებული მონაცემების დაფარვის პერიოდი უნდა იყოს მინიმუმ ხუთ

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:12
1. კოლექტიურად შეფასებული ფინანსური ინსტრუმენტები უნდა დაჯგუფდეს მსგავსი საკრედიტო რისკის მახასიათებლების მიხედვით. კომერციულმა ბანკებმა ჯგუფების იდენტიფიცირებისთვის უნდა გამოიყენონ ამ საერთო მახასიათებელთაგან ყველაზე რელევანტური. 2. ჯგუფები უნდა იყოს ფინანსური ინსტრუმენტების რაოდენობის მხრივ იმდენად დიდი და ფინანსური ინსტრუმენტების სახეობების მრავალფეროვნების მხრივ იმდენად პატარა, რომ უზრუნველყოს ჯგუფზე რელევანტური სტატისტიკური ანალიზის საკმარისი სანდოობა. 3. კომერციული ბანკების მიერ არ უნდა მო

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:13
1. მოსალოდნელი საკრედიტო ზარალის შემადგენელი კომპონენტების შესაფასებლად სხვადასხვა ჰომოგენური ჯგუფისთვის მოდელის აგება უნდა მოხდეს ცალ-ცალკე. ჰომოგენური ჯგუფის ფარგლებში უნდა გამოიყენებოდეს ერთი სახის მოდელები და იდენტური პარამეტრები. 2. მოსალოდნელი საკრედიტო ზარალის შეფასებისას გამოყენებული მოდელი რეკომენდებულია ითვალისწინებდეს ყველა შესაბამის შიდა თუ გარე ფაქტორს, რომელსაც გააჩნია კლიენტის გადახდისუნარიანობაზე გავლენის მოხდენის შესაძლებლობა, მათ შორის: სესხის მომსახურების კოეფიციენტის მიმდინარ

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:14
1. ისეთი პორტფელის შემთხვევაში, სადაც მონაცემები შეზღუდულია, რეკომენდებულია მიგრაციის მატრიცაზე დაფუძნებული მოდელების გამოყენება. მიგრაციის მატრიცა რეკომენდებულია დაეფუძნოს მსესხებლების რეიტინგებს. ვადაგადაცილებული დღეების მიხედვით მიგრაციის მატრიცის აგება შესაძლებელია, თუ კმაყოფილდება ყველა შემდეგი პირობა: ა) არ არსებობს მოცემული პორტფელის კლიენტების შიდა/გარე რეიტინგები; ბ) კლიენტების რეიტინგის მოძიება დაკავშირებულია არაგონივრულ ხარჯთან; გ) მონაცემთა შეზღუდულობის გამო მიგრაციის მატრიცისგან გან

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:15
1. LGD-ის შეფასების მეთოდოლოგია, სადაც შესაძლებელია, უნდა შემუშავდეს კომპონენტების დონეზე (შეფასების მიკრო-სტრუქტურული მიდგომა), იმგვარად, რომ LGD-ის გამოთვლა მოხდეს ძირითადი განმსაზღვრელი ფაქტორების მიხედვით. ამ უკანასკნელში მოიაზრება აღდგენის ალბათობა, აღდგენის დონე (ან დანაკარგების დონე) და ხელახლა გადეფოლტების ალბათობა. 2. აღდგენის დონის გაანგარიშება უნდა განხორციელდეს მოსალოდნელი აღდგენების მიმდინარე ღირებულების საშუალებით, რომელშიც გათვალისწინებული უნდა იყოს ყველა პირდაპირი დანახარჯი. უზრუ

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:16
1. EAD-ის გამოთვლის პროცესში კომერციულმა ბანკმა კონსერვატიულობის უზრუნველყოფის მიზნით არ უნდა აარიდოს თავი წინასწარ გადახდების მოდელირებას და ამასთანავე, უნდა გაითვალისწინოს საპროგნოზო ინფორმაცია, გარდა იმ შემთხვევისა, როდესაც დასაბუთებულია, რომ საპროგნოზო ინფორმაცია სტატისტიკურად მნიშვნელოვანი არ არის. 2. რევოლვირებადი ფინანსური ინსტრუმენტებისთვის უნდა განხორციელდეს მოსალოდნელი უტილიზაციის განსაზღვრა EAD ფაქტორის (EADF), კონვერსიის ფაქტორისა (CCF) ან/და სესხის ექვივალენტი ფინანსური ინსტრუმენტის

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:17
1. კომერციულ ბანკს შეუძლია გამოიყენოს ფასს 9-ით გათვალისწინებული გამარტივებული მიდგომა სავაჭრო მოთხოვნებისთვის, სახელშეკრულებო აქტივებისა და საიჯარო მოთხოვნებისთვის. 2. ამ მუხლით გათვალისწინებული გამარტივებული მიდგომით აღრიცხვის შემთხვევაში, აღნიშნული გაცხადებული უნდა იყოს კომერციული ბანკის სააღრიცხვო მეთოდოლოგიაში.

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:18
1. ვალიდაციის ეტაპზე შეიძლება იდენტიფიცირდეს მოდელთან დაკავშირებული გარკვეული შეზღუდვები სხვადასხვა გარემოების გამო, მათ შორის: ა) საკრედიტო რისკზე ზეგავლენის მქონე ფაქტორების გაუთვალისწინებლობა საკრედიტო რისკის რეიტინგისა და ECL-ის მოდელირების პროცესში; ბ) ახალი საკრედიტო რისკის ფაქტორების გაუთვალისწინებლობა, რომლებიც წარმოიშვა ეკონომიკური პირობების ცვლილების გამო; გ) მონაცემთა შეზღუდულობა; დ) მოდელის არასაკმარისი სიმძლავრე. 2. ამ მუხლის პირველი პუნქტით გათვალისწინებული შეზღუდვების კომპენსაცია

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:19
1. რეიტინგის გამოყენების შემთხვევაში კომერციულ ბანკს უნდა ჰქონდეს მოწესრიგებული საკრედიტო რისკის შეფასების პროცესი, რათა სწორად დააჯგუფოს ფინანსური ინსტრუმენტი საერთო საკრედიტო რისკის მახასიათებლების საფუძველზე. 2. სარეიტინგო სისტემამ უნდა უზრუნველყოს მსესხებლისა და ტრანზაქციის მახასიათებლების სათანადო შეფასება, რისკის სათანადო დიფერენციაცია და მისი ზუსტი და თანმიმდევრული რაოდენობრივი შეფასება.

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:20
1. რისკის დიფერენციაციის დონემ უნდა უზრუნველყოს, რომ რეიტინგში ფინანსური ინსტრუმენტის რაოდენობა საკმარისი იყოს მოცემული რეიტინგის ზარალის მახასიათებლების შესაფასებლად და ვალიდაციისათვის. ამასთან, მსესხებელთა რაოდენობის კონცენტრაცია არ უნდა იყოს გადაჭარბებული რომელიმე ჯგუფში; როგორც მნიშვნელოვანი კონცენტრაცია, ასევე ჯგუფში ზედმეტად მცირე მსესხებლების არსებობა დასაშვებია მხოლოდ იმ შემთხვევაში, თუ იგი დასაბუთებულია ამ მსესხებელთა რისკის ერთგვაროვნების დამაჯერებელი ემპირიული მტკიცებით. 2. კომერციული

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:21
1. საკრედიტო რისკის რეიტინგის მინიჭების ფუნქციის განვითარებამ უნდა მოიცვას უნივარიაციული და მრავალმხრივი ანალიზის ეტაპები. 2. უნივარიაციული ანალიზის ეტაპზე არსებული ცვლადებიდან შეირჩევა მაღალი დისკრიმინაციის უნარის მქონე ცვლადები, ჯინის კოეფიციენტის, ინფორმაციული მნიშვნელოვნების, სიზუსტის კოეფიციენტისა (accuracy ratio) და სხვ. მიხედვით. 3. მრავალმხრივი ანალიზის ეტაპზე ცვლადებს შორის კორელაციის შესასწავლად შეიძლება გამოყენებულ იქნეს იერარქიული კლასტერული ანალიზი და სხვ. მრავალმხრივი ანალიზისათვის

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:22
1. კომერციულ ბანკს შეუძლია გამოიყენოს მხოლოდ რეპუტაციული საკრედიტო შეფასების გარე ინსტიტუტების (სშგი) მიერ გამოქვეყნებული საკრედიტო რეიტინგები. 2. გარე რეიტინგების მინიჭების მეთოდოლოგია უნდა იყოს მდგრადი, სისტემატური და უნდა ექვემდებარებოდეს ისტორიულ გამოცდილებაზე დაფუძნებულ დამოუკიდებელ ვალიდაციას. რეიტინგების მონიტორინგი უნდა ხორციელდებოდეს მუდმივად, მათ შორის, შესაფასებელი სუბიექტის ფინანსური მდგომარეობის ცვლილებების შემთხვევაში. 3. კომერციულ ბანკს გარე რეიტინგის გამოყენების შემთხვევაში უნდა

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:23
1. კომერციულმა ბანკმა უნდა უზრუნველყოს კონტამინაციის პრინციპის დაცვა შემდეგი სახით: ა) საცალო და მიკრო პორტფელებისთვის მსესხებლის ერთ-ერთი ფინანსური ინსტრუმენტის საკრედიტო რისკის მნიშვნელოვანი ზრდა/გაუფასურება, როგორც წესი, გამოიწვევს ამავე მსესხებლის სხვა ფინანსური ინსტრუმენტების საკრედიტო რისკის მნიშვნელოვან გაზრდას/გაუფასურებას, მიუხედავად იმისა, ეს ინსტრუმენტები ერთ ჰომოგენურ ჯგუფში ხვდება თუ სხვადასხვაში; ბ) მცირე და საშუალო და კორპორატიული პორტფელების შემთხვევაში, ჯგუფის ერთ-ერთი ფინანსური

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:24
1. ეროვნული ბანკის შეფასებით, ფინანსური ინსტრუმენტის მე-3 დონის საკრედიტო რისკის კატეგორიის მინიჭების დროს ამ წესის მე-6 მუხლით გათვალისწინებულ კრიტერიუმებთან ერთად, მიზანშეწონილია, კომერციულმა ბანკმა იხელმძღვანელოს ცხრილ N1-ში მოცემული სესხის მომსახურების სარეკომენდაციო ზღვრებით: ცხრილი №1. PTI კოეფიციენტი 2. საკრედიტო რისკის კატეგორიის ცვლილებისას, იმ შემთხვევაში, თუ PTI კოეფიციენტი აღემატება საქართველოს ეროვნული ბანკის პრეზიდენტის 2020 წლის 13 მარტის N44/04 ბრძანებით დამტკიცებული „ფიზიკური პი

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:25
1.უზრუნველყოფის საშუალების საბაზრო ღირებულება უნდა შეფასდეს შეფასების საერთაშორისო სტანდარტების (IVS) შესაბამისად. 2. ფინანსური ინსტრუმენტის უზრუნველყოფის საშუალებად გამოყენებული უძრავი ქონების შეფასება და გადაფასება უნდა განხორციელდეს „კომერციული ბანკებისათვის უძრავი ქონების შეფასების ინსტრუქციის დამტკიცების თაობაზე“ საქართველოს ეროვნული ბანკის პრეზიდენტის 2018 წლის 14 მაისის N84/04 ბრძანების შესაბამისად. 3. შეფასებული უზრუნველყოფის საშუალების რეალური ღირებულების, რეალიზაციის პერიოდისა და რეალი

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > ARTICLE:26
კომერციული ბანკის მიერ ამ წესით გათვალისწინებული მოთხოვნების დარღვევის შემთხვევაში საქართველოს ეროვნული ბანკი უფლებამოსილია გამოიყენოს საქართველოს კანონმდებლობით განსაზღვრული საზედამხედველო ზომები ან/და სანქცია.

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > FOOTER:1

====================================================================================================
5682566
სახელმწიფო შესყიდვებთან დაკავშირებით გასატარებელი ზოგიერთი ღონისძიების შესახებ

TYPE=HEADER | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > HEADER:1
სახელმწიფო შესყიდვებთან დაკავშირებით გასატარებელი ზოგიერთი ღონისძიების შესახებ

TYPE=PREAMBLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > PREAMBLE:1


TYPE=ARTICLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > ARTICLE:1
„საქართველოს 2023 წლის სახელმწიფო ბიუჯეტის შესახებ“ საქართველოს კანონის 26-ე მუხლის „ბ“ ქვეპუნქტის შესაბამისად: 1. განისაზღვროს შესყიდვების ერთიანი ლექსიკონის (CPV კოდების) მიხედვით კლასიფიკატორის კოდები, რომელთა ფარგლებში საქართველოს მთავრობის/პრემიერ-მინისტრის კონტროლს დაქვემდებარებული/ანგარიშვალდებული საბიუჯეტო ორგანიზაციების მიერ, საქართველოს სამინისტროებისა და მათ კონტროლს დაქვემდებარებული საბიუჯეტო ორგანიზაციების მიერ, ასევე იმ საჯარო სამართლის იურიდიული პირების მიერ, რომელთა ხელმძღვანელებ

TYPE=ARTICLE | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > ARTICLE:2
დადგენილება ამოქმედდეს 2023 წლის 1 იანვრიდან და ძალაშია 2023 წლის 31 დეკემბრის ჩათვლით.

TYPE=FOOTER | ENCLOSURE=None | STRUCTURE=DOCUMENT:1 > FOOTER:1
პრემიერ-მინისტრი ირაკლი ღარიბაშვილი

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > HEADER:1
დანართი №1

TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > PREAMBLE:1


TYPE=ENCLOSURE | ENCLOSURE=1 | STRUCTURE=DOCUMENT:1 > ENCLOSURE:1 > POINT:1

# Inspect Structure

In [44]:
from collections import Counter

structure_patterns = Counter()

for d in docs:
    pattern = tuple(
        part["type"]
        for part in d.get("parts", [])
        if part.get("text")  # only non-empty parts
    )
    structure_patterns[pattern] += 1

for pattern, count in structure_patterns.most_common():
    print(f"{count:3} docs | " + " → ".join(pattern))


    unique_types = sorted({
    part["type"]
    for d in docs
    for part in d.get("parts", [])
    if part.get("text")
})

 27 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER
 19 docs | HEADER → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE
 19 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE
 16 docs | HEADER → POINT → FOOTER
 16 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE
 16 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE
 16 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
 14 docs | HEADER → ARTICLE → ARTICLE → FOOTER → ENCLOSURE
 13 docs | HEADER → ARTICLE → ARTICLE → FOOTER
 13 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE
 10 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE
 10 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE
  7 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  6 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE
  5 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  4 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  4 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE
  4 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → FOOTER
  4 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  4 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  4 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  3 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  3 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  3 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE
  3 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  2 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  2 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  2 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  2 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE
  2 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  2 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  2 docs | HEADER → PREAMBLE → POINT → POINT → FOOTER → ENCLOSURE
  2 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE
  2 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  2 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  1 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE
  1 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE
  1 docs | HEADER → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  1 docs | HEADER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → FOOTER
  1 docs | HEADER → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → POINT → FOOTER
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → POINT → POINT → POINT → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → FOOTER → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE
  1 docs | HEADER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → CHAPTER → FOOTER
  1 docs | HEADER → PREAMBLE → ARTICLE → ARTICLE → ARTICLE → FOOTER → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE → ENCLOSURE

In [43]:
print(unique_types)

['ARTICLE', 'CHAPTER', 'ENCLOSURE', 'FOOTER', 'HEADER', 'POINT', 'PREAMBLE']

In [40]:
for target_type in ["FOOTER", "POINT", "PREAMBLE"]:
    print(f"\n{'=' * 80}")
    print(f"{target_type}")
    print(f"{'=' * 80}")

    count = 0

    for d in docs:
        for part in d.get("parts", []):
            if part.get("type") == target_type and part.get("text"):
                print(f"\nDocument ID: {d['document_id']}")
                print(f"Title: {d['title']}")
                print(f"Structure: {' → '.join(part['structure'])}")
                print(f"Text: {part['text']}")

                count += 1

                if count == 3:
                    break

        if count == 3:
            break

================================================================================
FOOTER
================================================================================

Document ID: 7010313
Title: საქართველოს ეროვნული ბანკის 2026-2027 წლების ანგარიშგების გარე აუდიტის განსახორციელებლად დამოუკიდებელი აუდიტორული ფირმის (გარე აუდიტორის) არჩევის შესახებ
Structure: DOCUMENT:1 → FOOTER:1
Text: საქართველოს პარლამენტის თავმჯდომარე შალვა პაპუაშვილი თბილისი, 29 სექტემბერი 2026 წ. N1872-VIმს-XIმპ

Document ID: 7010249
Title: სახელმწიფო აუდიტის სამსახურის 2026-2027 წლების ფინანსური აუდიტის განსახორციელებლად აუდიტორული ფირმის არჩევის შესახებ
Structure: DOCUMENT:1 → FOOTER:1
Text: საქართველოს პარლამენტის თავმჯდომარე შალვა პაპუაშვილი თბილისი, 29 სექტემბერი 2026 წ. N1871-VIმს-XIმპ

Document ID: 7002597
Title: ადმინისტრაციული სახდელისგან გათავისუფლების შესახებ
Structure: DOCUMENT:1 → FOOTER:1
Text: საქართველოს პრეზიდენტი მიხეილ ყაველაშვილი თბილისი, 16 სექტემბერი 2026 წ. N1861/5-VIმს-XIმპ

================================================================================
POINT
================================================================================

Document ID: 7010313
Title: საქართველოს ეროვნული ბანკის 2026-2027 წლების ანგარიშგების გარე აუდიტის განსახორციელებლად დამოუკიდებელი აუდიტორული ფირმის (გარე აუდიტორის) არჩევის შესახებ
Structure: DOCUMENT:1 → POINT:1
Text: „საქართველოს ეროვნული ბანკის შესახებ“ საქართველოს ორგანული კანონის 59-ე მუხლის პირველი და მე-2 პუნქტებისა და საქართველოს პარლამენტის რეგლამენტის 160-ე მუხლის მე-9 პუნქტის შესაბამისად საქართველოს პარლამენტი ადგენს: 1. საქართველოს ეროვნული ბანკის 2026-2027 წლების ანგარიშგების გარე აუდიტის განმახორციელებელ დამოუკიდებელ აუდიტორულ ფირმად (გარე აუდიტორად) არჩეულ იქნეს აუდიტორული ფირმა – შპს „დელოიტი და ტუში“. 2. აუდიტორული შემოწმების სრული ღირებულება განისაზღვროს 427 160 ლარით. 3. საქართველოს ეროვნული ბანკის 2026-2027 წლების ანგარიშგების გარე აუდიტის ხარჯები გასწიოს საქართველოს ეროვნულმა ბანკმა. 4. დაევალოს საქართველოს ეროვნულ ბანკს, აუდიტორულ ფირმასთან – შპს „დელოიტი და ტუში“-სთან გააფორმოს ხელშეკრულება. 5. ეს დადგენილება ამოქმედდეს გამოქვეყნებისთანავე.

Document ID: 7010249
Title: სახელმწიფო აუდიტის სამსახურის 2026-2027 წლების ფინანსური აუდიტის განსახორციელებლად აუდიტორული ფირმის არჩევის შესახებ
Structure: DOCUMENT:1 → POINT:1
Text: „სახელმწიფო აუდიტის სამსახურის შესახებ“ საქართველოს ორგანული კანონის 35-ე მუხლისა და საქართველოს პარლამენტის რეგლამენტის 159-ე მუხლის მე-17 პუნქტის შესაბამისად საქართველოს პარლამენტი ადგენს: 1. სახელმწიფო აუდიტის სამსახურის 2026-2027 წლების ფინანსური აუდიტის განსახორციელებლად არჩეულ იქნეს აუდიტორული ფირმა – შპს „KPMG Georgia“. 2. აუდიტორული შემოწმების სრული ღირებულება განისაზღვროს 431 000 ლარით. 3. სახელმწიფო აუდიტის სამსახურის 2026-2027 წლების ფინანსური აუდიტის ხარჯები გასწიოს სახელმწიფო აუდიტის სამსახურმა. 4. დაევალოს სახელმწიფო აუდიტის სამსახურს, აუდიტორულ ფირმასთან – შპს „KPMG Georgia“-სთან გააფორმოს ხელშეკრულება. 5. ეს დადგენილება ამოქმედდეს გამოქვეყნებისთანავე.

Document ID: 7002597
Title: ადმინისტრაციული სახდელისგან გათავისუფლების შესახებ
Structure: DOCUMENT:1 → POINT:1
Text: მუხლი 1 ამ კანონის მიზანია ამავე კანონით გათვალისწინებული ადმინისტრაციული სახდელისგან − ჯარიმის აღუსრულებელი ნაწილისგან ერთჯერადი ხასიათის დროებითი და განსაკუთრებული ღონისძიების სახით იმ პირის გათავისუფლება, რომლის მიერ ადმინისტრაციული სამართალდარღვევის (გარდა 2025 წლის 1 მაისამდე ჩადენილი ადმინისტრაციული სამართალდარღვევისა) ჩადენისთვის მის მიმართ უფლებამოსილი პირის მიერ 2025 წლის 1 მაისიდან ამ კანონის ამოქმედებამდე არსებულ საანგარიშო პერიოდზე გამოცემული ადმინისტრაციული სახდელის დადების შესახებ დადგენილება არ აღსრულებულა. მუხლი 2 1. დამსაქმებელი გათავისუფლდეს საქართველოს ადმინისტრაციულ სამართალდარღვევათა კოდექსის 165 11 მუხლით გათვალისწინებული ადმინისტრაციული სამართალდარღვევის (გარდა 2025 წლის 1 მაისამდე ჩადენილი ადმინისტრაციული სამართალდარღვევისა) ჩადენისთვის დადებული ადმინისტრაციული სახდელისგან − ჯარიმის (მათ შორის, განმეორებითი ჯარიმის) აღუსრულებელი ნაწილისგან, თუ მის მიმართ ადმინისტრაციული სახდელის დადების შესახებ დადგენილება 2025 წლის 1 მაისიდან ამ კანონის ამოქმედებამდე არსებულ საანგარიშო პერიოდზე გამოსცა უფლებამოსილმა პირმა, ეს დადგენილება არ აღსრულებულა და დამსაქმებელმა საკუთარი ან დასაქმებულის სახელით საპენსიო შენატანის განხორციელებისა და მასზე დარიცხული საურავის გადახდის ვალდებულება სრულად შეასრულა ან იგი აღნიშნულ ვალდებულებას შეასრულებს არაუგვიანეს 2026 წლის 31 დეკემბრისა. 2. ამ მუხლით გათვალისწინებული ადმინისტრაციული სამართალდარღვევის ჩადენისთვის ადმინისტრაციული სახდელის სახით შეფარდებული ჯარიმა, რომელიც ამ კანონის ამოქმედების მომენტისთვის აღსრულებულია, დაბრუნებას არ ექვემდებარება. 3. ამ კანონის მოქმედება არ ვრცელდება ამ მუხლის პირველი პუნქტით გათვალისწინებულ ადმინისტრაციული სახდელის დადების შესახებ დადგენილებაზე, რომელიც უფლებამოსილმა პირმა ამ კანონის ამოქმედების შემდეგ ამავე კანონის ამოქმედებამდე პერიოდისთვის შეუსრულებელ ვალდებულებასთან დაკავშირებით გამოსცა. მუხლი 3 1. საქართველოს კანონმდებლობით განსაზღვრულმა ადმინისტრაციული სამართალდარღვევის საქმის განხილვის უფლებამოსილების მქონე ორგანომ, თანამდებობის პირმა და სასამართლომ ამ კანონის მე-2 მუხლით გათვალისწინებული ადმინისტრაციული სამართალდარღვევის საქმის განხილვა შეაჩერონ 2026 წლის 31 დეკემბრის ჩათვლით, გარდა იმ შემთხვევისა, როდესაც ამ კანონის ამოქმედების შემდეგ დაინტერესებული პირი შესაბამის ორგანოს, თანამდებობის პირს ან სასამართლოს ამ საქმის წარმოების გაგრძელების მოთხოვნით მიმართავს. ამ პუნქტით გათვალისწინებულ შემთხვევაში ჩერდება ადმინისტრაციული საჩივრის განხილვისთვის საქართველოს კანონმდებლობით დადგენილი ვადა. 2. ამ მუხლის პირველი პუნქტით გათვალისწინებული ადმინისტრაციული სამართალდარღვევის საქმის წარმოების შეჩერების პერიოდში საპენსიო შენატანის განხორციელების ვალდებულების შეუსრულებლობისთვის საურავის დარიცხვა არ შეჩერდება. 3. დამსაქმებელი თავისუფლდება ამ კანონის მე-2 მუხლით გათვალისწინებული გადაუხდელი ჯარიმის გადახდის ვალდებულებისგან, თუ მან საპენსიო შენატანის განხორციელებისა და მასზე დარიცხული საურავის გადახდის ვალდებულება სრულად შეასრულა ან იგი აღნიშნულ ვალდებულებას შეასრულებს არაუგვიანეს 2026 წლის 31 დეკემბრისა. 4. დამსაქმებლის მიერ ამ მუხლის მე-3 პუნქტით გათვალისწინებული პირობის შეუსრულებლობის შემთხვევაში ადმინისტრაციული სამართალდარღვევის საქმის განხილვის უფლებამოსილების მქონე ორგანომ, თანამდებობის პირმა და სასამართლომ გააგრძელონ ამ საქმის წარმოება შესაბამისი ეტაპიდან, საქართველოს კანონმდებლობით დადგენილი ვადის ფარგლებში. 5. საქართველოს იუსტიციის სამინისტროს მმართველობის სფეროში მოქმედმა საჯარო სამართლის იურიდიულმა პირმა − აღსრულების ეროვნულმა ბიურომ ამ კანონის საფუძველზე: ა) შეაჩეროს მის წარმოებაში არსებული, ამავე კანონის რეგულირების სფეროსთვის მიკუთვნებული ადმინისტრაციულ სამართალდარღვევათა საქმეების აღსრულება; ბ) არ დაიწყოს ამავე კანონის რეგულირების სფეროსთვის მიკუთვნებული ადმინისტრაციულ სამართალდარღვევათა საქმეების აღსრულება. 6. ამ მუხლის მე-3 პუნქტით გათვალისწინებული პირობის შესრულების შემთხვევაში საქართველოს იუსტიციის სამინისტროს მმართველობის სფეროში მოქმედმა საჯარო სამართლის იურიდიულმა პირმა − აღსრულების ეროვნულმა ბიურომ შეწყვიტოს აღსრულების საქმის წარმოება. 7. ამ მუხლის მე-3 პუნქტით გათვალისწინებული პირობის შესრულების შემთხვევაში თანამდებობის პირმა, შესაბამისმა ადმინისტრაციულმა ორგანომ ან სასამართლომ შეწყვიტოს ადმინისტრაციული საჩივრის განხილვის საქმის წარმოება, გარდა იმ შემთხვევისა, როდესაც მხარე მოითხოვს ამ საქმის წარმოების გაგრძელებას, რისთვისაც იგი არაუგვიანეს 2026 წლის 31 დეკემბრისა მიმართავს შესაბამის უფლებამოსილ ორგანოს ან სასამართლოს. 8. ამ კანონის ამოქმედებიდან 2026 წლის 31 დეკემბრის ჩათვლით საჯარო სამართლის იურიდიულმა პირმა − საქართველოს საპენსიო ფონდმა შეაჩეროს მის წარმოებაში არსებული, 2025 წლის 1 მაისიდან არსებული საანგარიშო პერიოდისთვის წარმოშობილი საპენსიო შენატანის განხორციელებისა და მასზე დარიცხული საურავის გადახდის შესახებ გადაწყვეტილების/ბრძანების აღსრულება და ეს გადაწყვეტილება/ბრძანება აღსასრულებლად არ გადასცეს საქართველოს იუსტიციის სამინისტროს მმართველობის სფეროში მოქმედ საჯარო სამართლის იურიდიულ პირს − აღსრულების ეროვნულ ბიუროს. 9. ამ კანონით განსაზღვრულ პირს ადმინისტრაციული სახდელისგან − ჯარიმისგან გასათავისუფლებლად არ მოეთხოვება ამ მუხლის პირველი პუნქტით გათვალისწინებული ორგანოსთვის, თანამდებობის პირისა და სასამართლოსთვის და საქართველოს იუსტიციის სამინისტროს მმართველობის სფეროში მოქმედი საჯარო სამართლის იურიდიული პირისთვის − აღსრულების ეროვნული ბიუროსთვის მიმართვა. 10. ამ კანონში გამოყენებულ ტერმინებს აქვს „დაგროვებითი პენსიის შესახებ“ საქართველოს კანონით განსაზღვრული მნიშვნელობები. მუხლი 4 ეს კანონი ამოქმედდეს გამოქვეყნებისთანავე.

================================================================================
PREAMBLE
================================================================================

Document ID: 6981470
Title: ვირტუალური აქტივის მომსახურების პროვაიდერის მიერ სტაბილური ვირტუალური აქტივის შესახებ ანგარიშგების შევსების და წარდგენის წესის დამტკიცების თაობაზე
Structure: DOCUMENT:1 → PREAMBLE:1
Text: „საქართველოს ეროვნული ბანკის შესახებ“ საქართველოს ორგანული კანონის მე-15 მუხლის პირველი პუნქტის „ზ“ ქვეპუნქტის, ამავე ორგანული კანონის 48-ე მუხლის პირველი და მე-3 პუნქტებისა და 52 5 მუხლის პირველი პუნქტის საფუძველზე, ვბრძანებ :

Document ID: 6969117
Title: ფასიანი ქაღალდების რეგისტრატორის და საბროკერო კომპანიის და მათი მმართველი ორგანოს წევრის მიმართ ფულის გათეთრებისა და ტერორიზმის დაფინანსების აღკვეთის ხელშეწყობის შესახებ საქართველოს კანონმდებლობის დარღვევისთვის ფულადი ჯარიმის ოდენობის განსაზღვრის, დაკისრებისა და აღსრულების წესის დამტკიცების თაობაზე
Structure: DOCUMENT:1 → PREAMBLE:1
Text: „საქართველოს ეროვნული ბანკის შესახებ“ საქართველოს ორგანული კანონის მე-15 მუხლის პირველი პუნქტის „ზ“ ქვეპუნქტის, 48-ე მუხლის პირველი, მე-3 და 4 1 პუნქტების, 52-ე მუხლის „თ“ ქვეპუნქტის, „ფასიანი ქაღალდების ბაზრის შესახებ“ საქართველოს კანონის 55 1 მუხლის, „ფულის გათეთრებისა და ტერორიზმის დაფინანსების აღკვეთის ხელშეწყობის შესახებ“ საქართველოს კანონის მე-4 მუხლის „გ“ ქვეპუნქტის და ამავე კანონის 38-ე მუხლის მე-6 პუნქტის საფუძველზე, ვბრძანებ:

Document ID: 6969072
Title: პირების მიმართ ფასიანი ქაღალდების შესახებ კანონმდებლობისა და „ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის შესახებ“ საქართველოს კანონის დარღვევისთვის ფულადი ჯარიმის ოდენობის განსაზღვრის, დაკისრებისა და აღსრულების წესის დამტკიცების თაობაზე
Structure: DOCUMENT:1 → PREAMBLE:1
Text: „საქართველოს ეროვნული ბანკის შესახებ“ საქართველოს ორგანული კანონის მე-15 მუხლის პირველი პუნქტის „ზ“ ქვეპუნქტის, 48-ე მუხლის მე-3 პუნქტის, 52-ე მუხლის „ზ“ და „თ“ ქვეპუნქტების, 52 4 მუხლის „ბ“ და „ზ“ ქვეპუნქტების, 52 7 მუხლის „ა“ და „გ“ ქვეპუნქტების, „ფასიანი ქაღალდების ბაზრის შესახებ“ საქართველოს კანონის 55-ე და 55¹ მუხლების, „იპოთეკით დაცული ობლიგაციების შესახებ“ საქართველოს კანონის 26-ე მუხლის, „ფასიან ქაღალდებად გარდაქმნის შესახებ“ საქართველოს კანონის 29-ე მუხლის, „საინვესტიციო ფონდების შესახებ“ საქართველოს კანონის 82-ე მუხლის, „ბუღალტრული აღრიცხვის, ანგარიშგებისა და აუდიტის შესახებ“ საქართველოს კანონის 23-ე მუხლის მე-2 პუნქტის, „ნებაყოფლობითი კერძო პენსიის შესახებ“ საქართველოს კანონის 52-ე მუხლის მე-5 პუნქტისა და „ნორმატიული აქტების შესახებ“ საქართველოს ორგანული კანონის 25-ე მუხლის პირველი პუნქტის „ბ“ ქვეპუნქტის საფუძველზე, ვბრძანებ:

In [39]:
import re
from collections import defaultdict

unique_types = sorted({
    part["type"]
    for d in docs
    for part in d.get("parts", [])
    if part.get("text")
})

# Georgian structural terms to search for
georgian_terms = {
    "მუხლი": "ARTICLE",
    "პუნქტი": "POINT",
    "თავი": "CHAPTER",
    "დანართი": "ENCLOSURE",
}

type_georgian = {}

for part_type in unique_types:
    matches = []

    for d in docs:
        for part in d.get("parts", []):
            if part.get("type") != part_type or not part.get("text"):
                continue

            text = part["text"]

            for georgian_name, mapped_type in georgian_terms.items():
                if mapped_type == part_type and re.search(
                    rf"(?<!\S){re.escape(georgian_name)}(?!\S)", text
                ):
                    matches.append(georgian_name)

    if matches:
        type_georgian[part_type] = max(set(matches), key=matches.count)

print(type_georgian)

{'ARTICLE': 'მუხლი', 'CHAPTER': 'თავი', 'ENCLOSURE': 'დანართი', 'POINT': 'პუნქტი'}

In [23]:
structure_counts = Counter()

for d in docs:
    for part in d.get("parts", []):
        enclosure = part.get("enclosure")

        if enclosure is None:
            location = "MAIN"
        else:
            location = f"ANNEX_{enclosure}"

        structure_counts[(location, part["type"])] += 1

for (location, part_type), count in structure_counts.most_common():
    print(f"{location:12} | {part_type:15} | {count:4}")

ANNEX_1      | ENCLOSURE       | 1378
MAIN         | ARTICLE         |  845
MAIN         | HEADER          |  300
MAIN         | PREAMBLE        |  300
MAIN         | FOOTER          |  300
MAIN         | CHAPTER         |  174
ANNEX_2      | ENCLOSURE       |   66
MAIN         | POINT           |   24
ANNEX_3      | ENCLOSURE       |    4
ANNEX_4      | ENCLOSURE       |    4
ANNEX_5      | ENCLOSURE       |    4
ANNEX_6      | ENCLOSURE       |    4

direct parent-child

In [45]:
from collections import Counter

relationships = Counter()

for d in docs:
    for part in d.get("parts", []):
        structure = part.get("structure", [])

        for parent, child in zip(structure, structure[1:]):
            parent_type = parent.split(":", 1)[0]
            child_type = child.split(":", 1)[0]

            relationships[(parent_type, child_type)] += 1

for (parent, child), count in relationships.most_common():
    print(f"{count:4} | {parent} → {child}")

1460 | DOCUMENT → ENCLOSURE
 845 | DOCUMENT → ARTICLE
 642 | ENCLOSURE → ARTICLE
 313 | CHAPTER → ARTICLE
 300 | DOCUMENT → HEADER
 300 | DOCUMENT → PREAMBLE
 300 | DOCUMENT → FOOTER
 213 | ENCLOSURE → HEADER
 213 | ENCLOSURE → PREAMBLE
 213 | ENCLOSURE → FOOTER
 174 | DOCUMENT → CHAPTER
 139 | ENCLOSURE → CHAPTER
  75 | ARTICLE → POINT
  40 | ENCLOSURE → POINT
  24 | DOCUMENT → POINT

In [24]:
def print_structure(doc):
    print("=" * 100)
    print(doc["document_id"])
    print(doc["title"])
    print()

    for part in doc["parts"]:
        structure = " → ".join(part["structure"])
        chars = len(part.get("text", ""))

        print(
            f"{part['type']:12} | "
            f"annex={part['enclosure']!s:4} | "
            f"{chars:7,} chars | "
            f"{structure}"
        )

In [25]:
print_structure(docs[0])

====================================================================================================
7010313
საქართველოს ეროვნული ბანკის 2026-2027 წლების ანგარიშგების გარე აუდიტის განსახორციელებლად დამოუკიდებელი აუდიტორული ფირმის (გარე აუდიტორის) არჩევის შესახებ

HEADER       | annex=None |     153 chars | DOCUMENT:1 → HEADER:1
PREAMBLE     | annex=None |       0 chars | DOCUMENT:1 → PREAMBLE:1
POINT        | annex=None |     758 chars | DOCUMENT:1 → POINT:1
FOOTER       | annex=None |      99 chars | DOCUMENT:1 → FOOTER:1

In [26]:
complexity = []

for d in docs:
    parts = d.get("parts", [])

    complexity.append({
        "document_id": d["document_id"],
        "title": d["title"],
        "parts": len(parts),
        "nonempty_parts": sum(bool(p.get("text")) for p in parts),
        "annexes": len({
            p["enclosure"]
            for p in parts
            if p.get("enclosure") is not None
        }),
        "characters": len(d.get("text", "")),
    })

complexity_df = pd.DataFrame(complexity)

display(
    complexity_df
    .sort_values(["annexes", "parts", "characters"], ascending=False)
    .head(20)
)

,document_id,title,parts,nonempty_parts,annexes,characters
9,6952872,სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-სა...,34,18,6,10783
247,5834965,მიკრობანკების კაპიტალის ადეკვატურობის მოთხოვნე...,74,68,2,101718
228,5840866,მიკრობანკების კიბერუსაფრთხოების მართვის ჩარჩოს...,29,24,2,32510
207,5936431,მსოფლიო ბანკთაშორისი საფინანსო ტელეკომუნიკაციე...,21,15,2,12363
210,5920196,აჭარის ავტონომიური რესპუბლიკის რესპუბლიკური ბი...,16,11,2,12817
110,6471596,"ენერგოაუდიტორების, ენერგოეფექტურობის სერტიფიკა...",15,8,2,54030
179,6103380,კომერციული ბანკის ლიკვიდაციისა და გადახდისუუნა...,15,9,2,53735
178,6103416,მიკროსაფინანსო ორგანიზაციის ლიკვიდაციის წესის ...,15,9,2,42063
222,5874397,აფხაზეთის ავტონომიური რესპუბლიკის ერთიანი სააღ...,14,8,2,123244
133,6279133,საქართველოს ეროვნული ბანკის მიერ ბოლო ინსტანცი...,14,10,2,17308
35,6823602,აფხაზეთის ავტონომიური რესპუბლიკის რესპუბლიკური...,14,7,2,10887
172,6120827,ცენტრალური დეპოზიტარის ლიკვიდაციისა და გადახდი...,13,8,2,40440
174,6120552,საბროკერო კომპანიის ლიკვიდაციისა და გადახდისუუ...,13,8,2,39828
122,6371452,აგროტურისტული და ღვინის ტურიზმის საქმიანობების...,13,8,2,13457
213,5901097,ფულის გათეთრებისა და ტერორიზმის დაფინანსების ა...,57,46,1,16012
266,5828443,აჭარის ავტონომიური რესპუბლიკის საბიუჯეტო პროცე...,52,49,1,58200
44,6793594,ანგარიშგების ვებგვერდზე გამოქვეყნებული ანგარიშ...,45,37,1,10367
196,5957864,კომერციული ბანკების ფულის გათეთრებისა და ტერორ...,39,36,1,53922
298,5679194,ფინანსური ინსტრუმენტების რისკის კატეგორიებისა ...,35,32,1,62705
245,5836263,მიკრობანკებისთვის ფინანსური ინსტრუმენტების რის...,34,31,1,61393

check docs that have a lot of annexes

In [27]:
max_annex_doc = max(
    docs,
    key=lambda d: len({
        p["enclosure"]
        for p in d.get("parts", [])
        if p.get("enclosure") is not None
    })
)

print_structure(max_annex_doc)

====================================================================================================
6952872
სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-საშტატო ცეცხლსასროლი იარაღის შენახვის, გაცემისა და აღრიცხვის წესის განსაზღვრის შესახებ

HEADER       | annex=None |     130 chars | DOCUMENT:1 → HEADER:1
PREAMBLE     | annex=None |     461 chars | DOCUMENT:1 → PREAMBLE:1
ARTICLE      | annex=None |     132 chars | DOCUMENT:1 → ARTICLE:1
ARTICLE      | annex=None |      43 chars | DOCUMENT:1 → ARTICLE:2
FOOTER       | annex=None |      68 chars | DOCUMENT:1 → FOOTER:1
ENCLOSURE    | annex=1    |       0 chars | DOCUMENT:1 → ENCLOSURE:1 → HEADER:1
ENCLOSURE    | annex=1    |       0 chars | DOCUMENT:1 → ENCLOSURE:1 → PREAMBLE:1
ENCLOSURE    | annex=1    |   1,725 chars | DOCUMENT:1 → ENCLOSURE:1 → ARTICLE:1
ENCLOSURE    | annex=1    |     444 chars | DOCUMENT:1 → ENCLOSURE:1 → ARTICLE:2
ENCLOSURE    | annex=1    |   1,527 chars | DOCUMENT:1 → ENCLOSURE:1 → ARTICLE:3
ENCLOSURE    | annex=1    |   1,807 chars | DOCUMENT:1 → ENCLOSURE:1 → ARTICLE:4
ENCLOSURE    | annex=1    |   1,818 chars | DOCUMENT:1 → ENCLOSURE:1 → ARTICLE:5
ENCLOSURE    | annex=1    |     685 chars | DOCUMENT:1 → ENCLOSURE:1 → ARTICLE:6
ENCLOSURE    | annex=1    |       0 chars | DOCUMENT:1 → ENCLOSURE:1 → FOOTER:1
ENCLOSURE    | annex=2    |      50 chars | DOCUMENT:1 → ENCLOSURE:2 → HEADER:1
ENCLOSURE    | annex=2    |       0 chars | DOCUMENT:1 → ENCLOSURE:2 → PREAMBLE:1
ENCLOSURE    | annex=2    |     278 chars | DOCUMENT:1 → ENCLOSURE:2 → ARTICLE:1
ENCLOSURE    | annex=2    |       0 chars | DOCUMENT:1 → ENCLOSURE:2 → FOOTER:1
ENCLOSURE    | annex=3    |     254 chars | DOCUMENT:1 → ENCLOSURE:3 → HEADER:1
ENCLOSURE    | annex=3    |       0 chars | DOCUMENT:1 → ENCLOSURE:3 → PREAMBLE:1
ENCLOSURE    | annex=3    |     422 chars | DOCUMENT:1 → ENCLOSURE:3 → ARTICLE:1
ENCLOSURE    | annex=3    |       0 chars | DOCUMENT:1 → ENCLOSURE:3 → FOOTER:1
ENCLOSURE    | annex=4    |       0 chars | DOCUMENT:1 → ENCLOSURE:4 → HEADER:1
ENCLOSURE    | annex=4    |       0 chars | DOCUMENT:1 → ENCLOSURE:4 → PREAMBLE:1
ENCLOSURE    | annex=4    |     695 chars | DOCUMENT:1 → ENCLOSURE:4 → ARTICLE:1
ENCLOSURE    | annex=4    |       0 chars | DOCUMENT:1 → ENCLOSURE:4 → FOOTER:1
ENCLOSURE    | annex=5    |       0 chars | DOCUMENT:1 → ENCLOSURE:5 → HEADER:1
ENCLOSURE    | annex=5    |       0 chars | DOCUMENT:1 → ENCLOSURE:5 → PREAMBLE:1
ENCLOSURE    | annex=5    |     134 chars | DOCUMENT:1 → ENCLOSURE:5 → ARTICLE:1
ENCLOSURE    | annex=5    |       0 chars | DOCUMENT:1 → ENCLOSURE:5 → FOOTER:1
ENCLOSURE    | annex=6    |       0 chars | DOCUMENT:1 → ENCLOSURE:6 → HEADER:1
ENCLOSURE    | annex=6    |       0 chars | DOCUMENT:1 → ENCLOSURE:6 → PREAMBLE:1
ENCLOSURE    | annex=6    |      76 chars | DOCUMENT:1 → ENCLOSURE:6 → ARTICLE:1
ENCLOSURE    | annex=6    |       0 chars | DOCUMENT:1 → ENCLOSURE:6 → FOOTER:1

In [28]:
print(max_annex_doc["document_id"])
print(max_annex_doc["title"])

6952872
სახელმწიფო აუდიტის სამსახურის სამსახურებრივ-საშტატო ცეცხლსასროლი იარაღის შენახვის, გაცემისა და აღრიცხვის წესის განსაზღვრის შესახებ

# Chunking logic

* Preserve the original Matsne document hierarchy and structure.
* Treat **Article** as the primary chunking unit whenever Articles exist.
* Keep all **Points** inside their parent Article; do not split Points into separate chunks.
* If a **Chapter contains Articles**, create one chunk per Article and keep the Chapter as hierarchical context.
* If a **Chapter does not contain Articles** but contains substantive content, use the Chapter as the chunk.
* Treat **Header** as contextual information and attach it to the relevant substantive chunks within the same structural branch.
* Treat **Preamble** as contextual information and attach it to the relevant Chapter/Article chunks within the same structural branch.

  * `DOCUMENT → PREAMBLE` applies to the relevant main-document chunks.
  * `ENCLOSURE → PREAMBLE` applies to the chunks within that enclosure.
* Treat **Footer** as metadata/provenance rather than retrieval content.
* Treat **Enclosure** as a structural container, not as a chunk by itself. Its Articles/Chapters are chunked using the same rules.
* Preserve the full hierarchy in each chunk's metadata, e.g. document → enclosure → chapter → article.
* Keep the **original text unchanged**; contextual information can be added to a separate `retrieval_text` used for embedding/retrieval.
* If a resulting legal unit is exceptionally large, only then apply a secondary size-based split while preserving its legal hierarchy and context.

# Extracting links to generate evaluation set

In [54]:
# ============================================================
# EXTRACT DOCUMENT NAMES + LINKS
# ============================================================

import csv
from urllib.parse import urljoin

# ============================================================
# CONFIGURATION
# ============================================================

BASE_URL = "https://matsne.gov.ge"
SEARCH_URL = f"{BASE_URL}/ka/document/search"

MAX_PAGES = 5
RESULTS_PER_PAGE = 100
REQUEST_DELAY = 1.0

OUTPUT_DIR = Path("../matsne_data")
RAW_SEARCH_DIR = OUTPUT_DIR / "search_pages"

RAW_SEARCH_DIR.mkdir(parents=True, exist_ok=True)

DOCUMENTS_FILE = OUTPUT_DIR / "documents.csv"

MAX_PAGES = 3

def extract_documents_from_page(html):
    soup = BeautifulSoup(html, "html.parser")

    documents = []

    # Find links that point to Matsne document pages
    for link in soup.find_all("a", href=True):

        href = link["href"]

        # Keep only actual document links
        if "/ka/document/view/" not in href:
            continue

        name = link.get_text(" ", strip=True)

        if not name:
            continue

        url = urljoin(BASE_URL, href)

        documents.append({
            "name": name,
            "url": url
        })

    return documents


# ============================================================
# EXTRACT FROM ALL SAVED SEARCH PAGES
# ============================================================

all_documents = []

for page in range(1, MAX_PAGES + 1):

    html_file = RAW_SEARCH_DIR / f"page_{page}.html"

    if not html_file.exists():
        print(f"Missing: {html_file}")
        continue

    html = html_file.read_text(
        encoding="utf-8"
    )

    page_documents = extract_documents_from_page(html)

    print(
        f"Page {page}: "
        f"{len(page_documents)} document links found"
    )

    all_documents.extend(page_documents)


# ============================================================
# REMOVE DUPLICATES
# ============================================================

unique_documents = {}

for document in all_documents:

    unique_documents[document["url"]] = document


all_documents = list(unique_documents.values())


# ============================================================
# SAVE CSV
# ============================================================

with open(
    DOCUMENTS_FILE,
    "w",
    encoding="utf-8-sig",
    newline=""
) as f:

    writer = csv.DictWriter(
        f,
        fieldnames=["name", "url"]
    )

    writer.writeheader()

    writer.writerows(all_documents)


# ============================================================
# SUMMARY
# ============================================================

print("\nExtraction complete.")
print(
    f"Unique documents found: "
    f"{len(all_documents)}"
)

print(
    f"Saved to: {DOCUMENTS_FILE}"
)

Page 1: 106 document links found
Page 2: 118 document links found
Page 3: 118 document links found

Extraction complete.
Unique documents found: 342
Saved to: ../matsne_data/documents.csv

In [55]:
eval_df = pd.read_csv("../evaluation/eval_questions.csv")

In [58]:
eval_df

,კითხვა,ოქროს_დოკუმენტი,დოკუმენტის_ID,წყარო,პასუხი
0,თუ საქართველოს ეროვნულ ბანკს 2026–2027 წლების ...,საქართველოს ეროვნული ბანკის 2026-2027 წლების ა...,7010313,"მუხლი 1, პუნქტები 1–5",გარე აუდიტორად არჩეულია შპს „დელოიტი და ტუში“....
1,რა განსხვავებაა სახელმწიფო აუდიტის სამსახურის ...,სახელმწიფო აუდიტის სამსახურის 2026-2027 წლების...,7010249,"მუხლი 1, პუნქტები 1–5",აუდიტორულ ფირმად არჩეულია შპს „KPMG Georgia“. ...
2,სახელმწიფო შესყიდვის დარეზერვებისას როგორ განი...,სახელმწიფო შესყიდვის დარეზერვების წესისა და პი...,6987795,"მუხლი 1, მუხლი 2",ეკონომიკურ ოპერატორთა წრე განისაზღვრება თავად ...
3,რა ინფორმაციის შეფასებას ემსახურება სტაბილური ...,ვირტუალური აქტივის მომსახურების პროვაიდერის მი...,6981470,"მუხლი 1, პუნქტები 2–3; მუხლი 2",ანგარიშგების მიზანია შეფასდეს ემიტენტის მიერ გ...
4,ფასიანი ქაღალდების რეგისტრატორის ან საბროკერო ...,ფასიანი ქაღალდების რეგისტრატორის და საბროკერო ...,6969117,"მუხლი 1, პუნქტები 8–9; მუხლი 2",გადახდილი ფულადი ჯარიმა მიემართება საქართველოს...
5,თუ პირს ფასიანი ქაღალდების ან ბუღალტრული აღრიც...,პირების მიმართ ფასიანი ქაღალდების შესახებ კანო...,6969072,"მუხლი 1, მუხლი 2","არა. დოკუმენტი პირდაპირ ადგენს, რომ ლიცენზიის,..."
6,რა არის საინვესტიციო ფონდების მხარდაჭერის სახე...,„საინვესტიციო ფონდების მხარდაჭერის სახელმწიფო ...,6961997,მუხლი 2; მუხლი 3,პროგრამის მიზანია საინვესტიციო ფონდების დაფუძნ...
7,აფხაზეთის ავტონომიური რესპუბლიკის რესპუბლიკური...,აფხაზეთის ავტონომიური რესპუბლიკის რესპუბლიკური...,6951831,მუხლი 1,ბრძანებით მტკიცდება აფხაზეთის ავტონომიური რესპ...
8,აგროთანადაფინანსების სახელმწიფო პროგრამის შემთ...,აგროთანადაფინანსების სახელმწიფო პროგრამის დამტ...,6906141,მუხლი 1; მუხლი 2; დანართი,დადგენილებით მტკიცდება თანდართული „აგროთანადაფ...
9,რა ცვლილებას ახდენს ეროვნული ბანკის 2026 წლის ...,სესხის გამცემი ორგანიზაციების მიერ 1 000 000 ლ...,6892788,მუხლი 1; მუხლი 2; მუხლი 3,ახალი ბრძანება ეხება სესხის გამცემი ორგანიზაცი...
10,IFRS-ის 2026 წლის გამოცემის ქართულ ენაზე შემოღ...,ფინანსური ანგარიშგების საერთაშორისო სტანდარტებ...,6885351,მუხლი 1,"ბრძანება გამოცემულია „ბუღალტრული აღრიცხვის, ან..."
11,ინფრასტრუქტურულ პროექტში ფასების ცვლილებით გამ...,ინფრასტრუქტურული პროექტების განხორციელების ხელ...,6883523,მუხლი 1; მუხლი 2; მუხლი 16,ფასთა ინდექსაციის მიზანია წესით გათვალისწინებუ...
12,სამშენებლო სამუშაოების სახელმწიფო შესყიდვისას ...,ტექნიკური რეგლამენტის — სამშენებლო სამუშაოების...,6880931,მუხლი 1; მუხლი 2; დანართი — ტექნიკური რეგლამენტი,რეგლამენტი ადგენს სამშენებლო სამუშაოების სახელ...
13,რატომ ახორციელებს ცენტრალური შემსყიდველი ორგან...,ცენტრალური შემსყიდველი ორგანოს მიერ ბაზრის კვლ...,6878133,მუხლი 1; მუხლი 2,ცენტრალური შემსყიდველი ორგანო ბაზრის კვლევას კ...
14,ცენტრალიზებული შესყიდვების განხორციელებასთან დ...,ცენტრალიზებული შესყიდვების განხორციელებასთან დ...,6878077,მუხლი 1; მუხლი 2,დადგენილება ადგენს ცენტრალიზებულ შესყიდვებთან ...
15,რა სამართლებრივი შესაძლებლობები აქვს ცენტრალურ...,საჯარო სამართლის იურიდიული პირის – ცენტრალური ...,6878066,"მუხლი 1; თავი II, მუხლი 2",ცენტრალურ შემსყიდველ ორგანოს საკუთარი სახელით ...
16,ცენტრალიზებული შესყიდვის წესის მიზნებიდან გამო...,ცენტრალიზებული შესყიდვის განხორციელების წესისა...,6878099,მუხლი 1; მუხლი 2,წესი შემუშავებულია „სახელმწიფო შესყიდვების შეს...
17,სახელმწიფო შესყიდვების სააგენტოში თანამდებობის...,სახელმწიფო შესყიდვების სააგენტოში თანამდებობებ...,6873010,თავი II — თავმჯდომარის მოადგილე; მუხლი 2,დოკუმენტი ეყრდნობა „სახელმწიფო შესყიდვების შეს...
18,სახელმწიფო შესყიდვების სააგენტოს სტრუქტურული ე...,სახელმწიფო შესყიდვების სააგენტოს სტრუქტურული ე...,6873045,"მუხლი 1; თავი II, მუხლი 2",სააგენტოს სტრუქტურული ერთეულებისა და თანამშრომ...
19,რა სამართლებრივი ფუნქცია აქვს IESBA Code-ის ქა...,პროფესიონალი ბუღალტრების ეთიკის საერთაშორისო კ...,6858936,მუხლი 1,ბრძანების მიზანია პროფესიონალი ბუღალტრების ეთი...
20,სახელმწიფო აუდიტის სამსახურის მიერ ადმინისტრაც...,სახელმწიფო აუდიტის სამსახურის მიერ ადმინისტრაც...,6858170,მუხლი 1,დოკუმენტი აწესრიგებს სახელმწიფო აუდიტის სამსახ...
21,სახელმწიფო შესყიდვების სააგენტოს რეორგანიზაციი...,საჯარო სამართლის იურიდიული პირის – სახელმწიფო ...,6850322,"მუხლი 1; თავი II, მუხლი 2",დადგენილებით ხორციელდება სააგენტოს რეორგანიზაც...
22,როგორ განასხვავებს ინციდენტის განსაზღვრის წესი...,ადამიანის ძირითადი უფლებებისა და თავისუფლებები...,6843012,მუხლი 2; თავი II; მუხლი 3,"მუხლი 2 ადგენს, რომ წესში გამოყენებულ ტერმინებ..."
23,ფინანსთა სამინისტროს აკადემიის ანაზღაურებადი მ...,საჯარო სამართლის იურიდიული პირის – ფინანსთა სა...,6838183,მუხლი 1; მუხლი 2,წესი განსაზღვრავს ფინანსთა სამინისტროს აკადემი...
24,ფაქტორინგის სამართლებრივი ბუნებიდან გამომდინარ...,ფაქტორინგის შესახებ,6825189,მუხლი 3; მუხლი 12; მუხლი 14; მუხლი 15,ფაქტორინგი გულისხმობს დებიტორული დავალიანების ...
25,ლიკვიდაციის პროცესში მყოფი ეროვნული ბანკის ზედ...,საქართველოს ეროვნული ბანკის ზედამხედველობას და...,6827122,მუხლი 1,ბრძანება გამოცემულია საქართველოს ეროვნული ბანკ...
26,აფხაზეთის ავტონომიური რესპუბლიკის ბიუჯეტის ასი...,აფხაზეთის ავტონომიური რესპუბლიკის რესპუბლიკური...,6823602,მუხლი 2; მუხლი 3,"ძველი, 2013 წლის 13 მარტის №5 დადგენილება ძალა..."
27,ჭკვიანი მარშრუტიზაციის სტანდარტთან დაკავშირებუ...,"ჭკვიანი მარშრუტიზაციის სტანდარტის განხილვის, ჭ...",6819297,მუხლი 1; მუხლი 2; დანართი,მუხლი 1-ით დამტკიცებულია თანდართული „ჭკვიანი მ...
28,პროფესიული განათლების მასწავლებელთა შრომის ანა...,სახელმწიფოს მიერ ან მისი მონაწილეობით დაფუძნებ...,6797388,მუხლი 2; მუხლი 3,"ძველი, 2024 წლის 15 ოქტომბრის №160/ნ ბრძანება ..."
29,საინვესტიციო ოქროს სტატუსის დასადგენად დამატებ...,საინვესტიციო ოქროს სტატუსის დადგენის დამატებით...,6810516,მუხლი 1; დანართი,დოკუმენტი ერთდროულად ამტკიცებს საინვესტიციო ოქ...
30,სახელმწიფო აუდიტის სამსახურში შიდა კონკურსის ჩ...,სახელმწიფო აუდიტის სამსახურის საშტატო ნუსხით გ...,6810004,მუხლი 1; მუხლი 2; დანართი №1,მტკიცდება შიდა კონკურსის გამოცხადებისა და ჩატა...
31,სტიქიის პრევენციის სახელმწიფო პროგრამის დაფინა...,სტიქიის პრევენციის სახელმწიფო პროგრამის დამტკი...,6802692,მუხლი 2; მუხლი 3,პროგრამის დაფინანსება ხორციელდება საქართველოს ...
32,2027–2030 წლების ქვეყნის ძირითადი მონაცემებისა...,2027 − 2030 წლების ქვეყნის ძირითადი მონაცემები...,6799583,მუხლი 1,2026 წლის 12 მარტამდე სამინისტროებმა შესაბამის...
33,ანგარიშგების ვებგვერდზე გამოქვეყნებული ანგარიშ...,ანგარიშგების ვებგვერდზე გამოქვეყნებული ანგარიშ...,6793594,"მუხლი 1; დანართი, მუხლი 1",მტკიცდება „ანგარიშგების ვებგვერდზე გამოქვეყნებ...
34,ადმინისტრაციული სამართალდარღვევის საქმისწარმოე...,ადმინისტრაციული სამართალდარღვევის საქმეზე შესა...,6789854,მუხლი 1; დანართები №1–№5,მტკიცდება ადმინისტრაციული სამართალდარღვევის სა...
35,ვადაგადაცილებული სასესხო დავალიანებების რესტრუ...,საქართველოს ფინანსთა სამინისტროსთან შექმნილი ვ...,6787667,მუხლი 2; მუხლი 3,2011 წლის 14 ივნისის №236 დადგენილება ძალადაკა...
36,სასამართლო ექსპერტიზის ეროვნული ბიუროს მომსახუ...,საჯარო სამართლის იურიდიული პირის – ლევან სამხა...,6768600,მუხლი 1; დანართი,ტარიფები მტკიცდება შესაბამისი ნორმატიული აქტით...
37,საქართველოს პროკურატურის თანამშრომელთა ანაზღაუ...,საქართველოს პროკურატურის თანამშრომელთა თანამდე...,6754241,მუხლი 1; დანართები №1–№6,თანამდებობრივი სარგოს ოდენობები განისაზღვრება ...
38,2025 წლის 17 დეკემბრამდე ჩარიცხული სტუდენტების...,2025 წლის 17 დეკემბრამდე უმაღლეს საგანმანათლებ...,6755100,მუხლი 1; მუხლი 2,"წესი ეხება იმ პირებს, რომლებიც უმაღლეს საგანმა..."
39,რეაბილიტაცია-ადაპტაციის ეროვნული ცენტრის სპეცი...,შპს რეაბილიტაცია-ადაპტაციის ეროვნული ცენტრის მ...,6747765,მუხლი 1; დანართი,სპეციალური წესი ეხება იმ მარაგ-ნაწილებისა და ტ...
40,საქართველოს ენერგეტიკის განვითარების ფონდის მი...,სს საქართველოს ენერგეტიკის განვითარების ფონდის...,6747511,მუხლი 1; დანართი,აქტი ადგენს საქართველოს ენერგეტიკის განვითარებ...
41,2026 წლის სახელმწიფო შესყიდვების წინასწარი თან...,სახელმწიფო შესყიდვებთან დაკავშირებით გასატარებ...,6748166,მუხლი 1; დანართები №1–№3,დანართი №1-ის შესაბამისი CPV კოდების ფარგლებში...
42,შემსყიდველი ორგანიზაციის მიერ ბაზრის კვლევის ჩ...,შემსყიდველი ორგანიზაციის მიერ ბაზრის კვლევის გ...,6727186,მუხლი 1; მუხლი 2,ბაზრის კვლევა უნდა ემსახურებოდეს შესყიდვისთვის...
43,2026 წლის სამედიცინო დაწესებულებების რეაბილიტა...,სამინისტროს სისტემაში შემავალ სამედიცინო და სხ...,6740933,მუხლი 1; პროგრამის დანართი,დადგენილებით მტკიცდება 2026 წლის სახელმწიფო პრ...
44,საქართველოს სახელმწიფო ელექტროსისტემის სპეციალ...,სს – საქართველოს სახელმწიფო ელექტროსისტემის მი...,6733968,მუხლი 1; დანართი,აქტი ადგენს სს „საქართველოს სახელმწიფო ელექტრო...
45,საქართველოს ფოსტის სპეციალური შესყიდვების წესი...,შპს საქართველოს ფოსტის მიერ საქონლისა და მომსა...,6733900,მუხლი 1; დანართი,რეგულირების ობიექტია შპს საქართველოს ფოსტის მი...
46,საქართველოს აეროპორტების გაერთიანების სპეციალუ...,შპს საქართველოს აეროპორტების გაერთიანების მიერ...,6734004,მუხლი 1; დანართი,"დადგენილება წარმოადგენს სამართლებრივ აქტს, რომ..."